### ISSUE TITLE
使用vue的eslint的时候提示大段错误

### ISSUE THREAD

**Issue by kelekexiao123** [AlloyTeam/eslint-config-alloy#11]
在每一个vue文件里的第一行都会提示规则未找到，怀疑插件是否被正确安装。
![image](https://user-images.githubusercontent.com/17807197/31860191-1f8802b2-b749-11e7-9c40-fb47ddd2cdbe.png)

包安装版本如下：
![image](https://user-images.githubusercontent.com/17807197/31860171-ed298aac-b748-11e7-9672-c3334a911152.png)

**Comment by lcxfs1991** [comment]
你是使用什么IDE呀？

**Comment by kelekexiao123** [comment]
嗯，就是vscode。而且我也按要求配置了eslint.validate的。

**Comment by lcxfs1991** [comment]
这样子试试？
```javascript
module.exports = {
    "extends": [
      "eslint-config-alloy/vue"
    ],
    "plugins": [
      "vue"
    ],
    "globals": {
        
    }
```

**Comment by kelekexiao123** [comment]
加了plugins之后问题仍然存在。
![image](https://user-images.githubusercontent.com/17807197/31869040-c9a7a94e-b7d7-11e7-9bb1-6d6989145e6d.png)

**Comment by lcxfs1991** [comment]
会不会缺少了一些依赖呢？

npm install --save-dev eslint-config-alloy eslint-plugin-vue babel-eslint

**Comment by kelekexiao123** [comment]
嗯，不是的。node_modules都删过重装了，跟eslint相关的依赖版本我已经发在上面了。

**Comment by lcxfs1991** [comment]
definition not found感觉是有些依赖找不到。

我们团队搭的vue脚手架，使用的eslint-config-alloy，用vscode没问题。

https://github.com/steamerjs/steamer-vue

**Comment by kelekexiao123** [comment]
我发现即使使用vue-cli使用这个eslint也能将问题重现。

ps：eslint中，文件保存自动修复代码的语句是哪一条呢？在vscode里，配置了"eslint.autoFixOnSave": true好像也不行

**Comment by lcxfs1991** [comment]
那可能是你的 vscode的配置问题吧？

**Comment by kelekexiao123** [comment]
我也觉得有可能，能将vscode配置参考一下么

**Comment by lcxfs1991** [comment]
```javascript
{
    "eslint.validate": [
        {
            "language": "html",
            "autoFix": true
        },
        {
            "language": "vue",
            "autoFix": true
        },
        {
            "language": "javascript",
            "autoFix": true
        },
        {
            "language": "javascriptreact",
            "autoFix": true
        }
    ],
    "eslint.options": {
        "extensions": [".html", ".js", ".vue", ".jsx"]
    },
    "emmet.syntaxProfiles": {
        "vue-html": "html",
        "vue": "html"
    }
}
```

**Comment by lcxfs1991** [comment]
正常了吗？

**Comment by wanghaoxi3000** [comment]
用vscode同样出现了这个问题...
![qq 20171104014929](https://user-images.githubusercontent.com/10104549/32388375-6d6b078c-c102-11e7-8f00-739c02268009.png)

**Comment by lcxfs1991** [comment]
@wanghaoxi3000 重装一下依赖，以及文档vue的步骤处理一下看看？

**Comment by xcatliu** [comment]
@kelekexiao123 @wanghaoxi3000 估计是因为 eslint-plugin-vue 的版本不对，试一下安装 v3 以上：

```bash
npm install eslint-plugin-vue@3
```

**Comment by wanghaoxi3000** [comment]
@xcatliu 
重新使用npm install eslint-plugin-vue@3 后正常了，应该就是这个版本的问题了
