### ISSUE TITLE
[no-invalid-this] 规则不支持 typescript 中类属性检测

### ISSUE THREAD

**Issue by huhamhire** [AlloyTeam/eslint-config-alloy#112]
会导致 typescript 中类属性对于 this 引用产生额外 eslint 报错。

参见
https://github.com/typescript-eslint/typescript-eslint/issues/491

在类属性申明中使用 this 属于常见的行为，比如模板字符串的组合拼接。

**Comment by xcatliu** [comment]
已在 typescript 规则中关闭 `no-invalid-this`

**Comment by RainyLiao** [comment]
> 已在 typescript 规则中关闭 `no-invalid-this`

不是说已关闭这条规则吗，最新的还有，是什么原因又开启了呢？
