### ISSUE TITLE
[ eslint Error ] eslint-config-alloy/typescript': Cannot find module '@typescript-eslint/eslint-plugin'

### ISSUE THREAD

**Issue by psaren** [AlloyTeam/eslint-config-alloy#115]
eslint info
`
Info  - 上午11:51:46] ESLint server stopped.
[Info  - 上午11:51:47] ESLint server running in node v10.11.0
[Info  - 上午11:51:47] ESLint server is running.
[Info  - 上午11:51:49] ESLint library loaded from: e:\wamp64\www\ppwStatic\app\node_modules\eslint\lib\api.js
[Error - 上午11:51:51] 
Failed to load plugin '@typescript-eslint' declared in 'app\.eslintrc.js » eslint-config-alloy/typescript': Cannot find module '@typescript-eslint/eslint-plugin'
Require stack:
- E:\wamp64\www\ppwStatic\__placeholder__.js
Happened while validating E:\wamp64\www\ppwStatic\app\src\App.tsx
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure '@typescript-eslint/eslint-plugin' is installed globally as well.
3. If ESLint is installed locally, then '@typescript-eslint/eslint-plugin' isn't installed correctly.

Consider running eslint --debug E:\wamp64\www\ppwStatic\app\src\App.tsx from a terminal to obtain a trace about the configuration files used.
`
I had tried install '@typescript-eslint/eslint-plugin' globally, but it is still not work!
This app is created by npx create-react-app app --typescript
The .vscode/settings.json, .eslintrc.js, package.json are below

![setting info](https://i.ibb.co/HnpZrZY/1.png)

So  how should I fix it?

**Comment by xcatliu** [comment]
Try uninstall and install all modules:

```bash
npm uninstall --save-dev eslint typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint-plugin-react eslint-config-alloy
```

```bash
npm install --save-dev eslint typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint-plugin-react eslint-config-alloy
```

**Comment by psaren** [comment]
@xcatliu 
I had tried to do what you sugguest, but I still got the same error.

**Comment by xcatliu** [comment]
Please create a repo which can reproduce this issue

**Comment by psaren** [comment]
Here is the repo to reproduce.
[reproduce repo](https://github.com/psaren/pp-static-repo)
``` bash
cd app
npm install
```

**Comment by xcatliu** [comment]
https://github.com/psaren/pp-static-repo/pull/1

**Comment by psaren** [comment]
@xcatliu I have been merge your PR, but it still not work for me.
![alt image](https://i.ibb.co/dtyLPdh/20191104222510.png)

**Comment by psaren** [comment]
I try to create-react-app without --typescript option,
I  set up eslint config following the README  of eslint-config-alloy, and it work well.

**Comment by xcatliu** [comment]
![image](https://user-images.githubusercontent.com/5453359/68173111-d8eb3480-ffb4-11e9-9d71-72be01a451d1.png)

Please try reclone and reinstall node modules.
It works for me.

**Comment by psaren** [comment]
Thanks, it works for me too now!

But why the msg vars (in line 4)  is not show lint error?
Whether the rule [no-unused-vars] is disabled ?

**Comment by xcatliu** [comment]
Please see https://github.com/AlloyTeam/eslint-config-alloy/issues/65

**Comment by psaren** [comment]
Thank you!
