### ISSUE TITLE
关于空catch块的看法

### ISSUE THREAD

**Issue by erasermeng** [AlloyTeam/eslint-config-alloy#12]
https://github.com/AlloyTeam/eslint-config-alloy/blob/9de217dc07f2a0d506353ba8eb749aa46a09f8f9/index.js#L80

空的catch绝大多数的情况下是一个bad practice，尤其是对于新手来说，只有在极少数的情况下，当对发生的错误无能为力的时候才会用到，因此我认为最佳实践是直接禁止空catch块，在极少数有必要的情况下注释说明，这样可以有效防止新人将错误掩盖的行为。

**Comment by lcxfs1991** [comment]
有一定道理，与其空catch块，不如暴露出来

**Comment by xcatliu** [comment]
同意，如果必须为空 catch，则需要加上注释说明原因

**Comment by xcatliu** [comment]
试了下，把 `allowEmptyCatch: true` 去掉后，eslint 仍然允许 empty catch，故允许空 catch 是其默认行为，看了下 airbnb 也是允许空 catch 的。

设为 `false` 之后，在我们代码中运行了一下，发现空 catch 这种用法还是很常见的，并不是极少数。并且合理的——有的代码希望即使报错也不影响后续运行。

新人将错误掩盖是价值观问题，即使这里强制要求不允许空 catch，新人也可以加 `/* eslint no-empty:0 */` 覆盖 eslint 配置。

故这里不做更改。
