### ISSUE TITLE
请教关于 site/config 下的 json 文件问题

### ISSUE THREAD

**Issue by tsingwong** [AlloyTeam/eslint-config-alloy#121]
如题，在学习该代码库的时候遇到下面两个问题，想请教下大佬

1. site/config 下的这几个 json文件是生成的，还是手动维护的呀？

2. site/config/xxx.json 中的 badExample 和 goodExample 是咋生成

多谢指点

Thanks♪(･ω･)ﾉ

**Comment by xcatliu** [comment]
如 [README.md](https://github.com/AlloyTeam/eslint-config-alloy#contributing) 所说，此项目已经实现高度的自动化，一切能自动化实现的地方都是自动化的。

1. site/config 中的文件是执行 `npm run build` 生成的
2. badExample 和 goodExample 也是 `npm run build` 时生成的，其中使用到了 fs, Prism, insertTag 等模块

具体脚本可以看 [scripts/build.ts](https://github.com/AlloyTeam/eslint-config-alloy/blob/master/scripts/build.ts) 文件

**Comment by tsingwong** [comment]
好哒， 前面没有注意看到最下面的说明。

多谢大佬指点~~
