### ISSUE TITLE
@typescript-eslint/prefer-function-type问题

### ISSUE THREAD

**Issue by eagle1098** [AlloyTeam/eslint-config-alloy#126]
@typescript-eslint/prefer-function-type的注释为"可以简写为函数类型的接口或字面类型的话，则必须简写"，但npm上的解释为"Use function types instead of interfaces with call signatures"，是否理解有误？
如果打开这个检查，则函数类型的接口都被报错。

**Comment by xcatliu** [comment]
中文解释基本上就是英文的直译吧，感觉不太好描述。
或许按下面这么描述？

可以简写为函数类型的接口或对象字面类型的话，则必须简写

**Comment by eagle1098** [comment]
用函数类型别名代替函数类型接口来调用签名。不是这个意思吗？

**Comment by xcatliu** [comment]
使用函数类型别名替代包含函数调用签名的接口

这样应该准确一些？

**Comment by eagle1098** [comment]
总之，我觉得是用别名代替接口的意思，也符合程序的行为。原来的注释确实让我没明白。

**Comment by xcatliu** [comment]
那就按这个改吧

使用函数类型别名替代包含函数调用声明的接口

**Comment by xcatliu** [comment]
已更新，感谢建议！
