### ISSUE TITLE
[规则问题]no-extra-parens

### ISSUE THREAD

**Issue by erasermeng** [AlloyTeam/eslint-config-alloy#13]
https://github.com/AlloyTeam/eslint-config-alloy/blob/9de217dc07f2a0d506353ba8eb749aa46a09f8f9/index.js#L89

https://eslint.org/docs/rules/no-extra-parens
规则原文是禁止多余的括号，嵌套的二元表达式只是all中的一个选项而已，函数表达式中的括号理应被禁止，而条件语句、return语句、嵌套二元表达式、箭头函数等可以允许多余的括号。

如：
```
/* eslint no-extra-parens: ["error", "functions"] */

((function foo() {}))();

var y = (function () {return 1;});
```

这类多余的括号就是一种非常不好的实现

建议配置为：
`'no-extra-parens': ['error', 'functions']`

**Comment by xcatliu** [comment]
同意，有道理，感谢建议！
