### ISSUE TITLE
TypeScript 版本应该禁用某些 eslint-config-alloy 的规则

### ISSUE THREAD

**Issue by xiaoxiangmoe** [AlloyTeam/eslint-config-alloy#130]
*  no-undefined 在 ts 中是不合理的，因为 undefined 是 ts 的类型之一，类型和值都是 undefined 会很统一
* yoda 之类的规则，在类型检查的加持下，也显得没有必要了

---

也许我们可以单独维护一个 ts 友好版本的 eslint-config-alloy，并且给出 ts 特有的解释文档。

**Comment by xcatliu** [comment]
感谢建议！

- `no-undefined` 在 eslint-config-alloy 中本来就被关闭了
- `yoda` 我理解应该是一种风格问题，而不是类型问题

---

实际上 eslint-config-alloy 的 ts 规则就是 ts 友好的。部分不兼容的、或者不适合在 ts 中开启的规则，已经在 ts 的 [`.eslintrc.js` 中关闭了](https://github.com/AlloyTeam/eslint-config-alloy/blob/master/test/typescript/.eslintrc.js)

只是目前确实缺少这部分的特有的解释文档，后续我考虑一下该如何补充进来

**Comment by xiaoxiangmoe** [comment]
no-cond-assign 可以部分代替 yoda；然后需要布尔值的情况，用类型检查可以再代替部分 yoda……所以 yoda 看起来是冗余的。
