### ISSUE TITLE
[规则问题]no-prototype-builtins

### ISSUE THREAD

**Issue by erasermeng** [AlloyTeam/eslint-config-alloy#14]
https://github.com/AlloyTeam/eslint-config-alloy/blob/9de217dc07f2a0d506353ba8eb749aa46a09f8f9/index.js#L117

[https://eslint.org/docs/rules/no-prototype-builtins](https://eslint.org/docs/rules/no-prototype-builtins)

原文规则应该是指不允许直接使用`hasOwnProperty`等方法，要通过`call`方式调用，因为通过`Object.create(null)`出来的对象没有继承自`Object.prototype`，这项规则不应该被`off`

**Comment by lcxfs1991** [comment]
@erasermeng 在某些低版本浏览器里，可能会出问题，之前就被坑过。这条建议维持现状。

**Comment by erasermeng** [comment]
@lcxfs1991 多谢回答，建议这个原因可以加到注释里哈

**Comment by xcatliu** [comment]
感谢建议，这里的注释确实写的有问题，我会修改过来。

**Comment by xcatliu** [comment]
这个规则的含义是禁止直接在对象上调用 `hasOwnProperty` 方法，而必须使用 `Object.prototype.hasOwnProperty.call`

给出的理由是，使用 `Object.create(null)` 创建的对象，是没有 `hasOwnProperty` 的，直接调用它的 `hasOwnProperty` 就会报错。

不过我们一般是使用 `{}` 来创建空对象的，`Object.create(null)` 用的很少，所以这个规则可以设置为 `off`，使用了 `Object.create(null)` 的人自己去注意别直接调用 `hasOwnProperty` 即可。
