### ISSUE TITLE
建议添加 @typescript-eslint/indent 规则

### ISSUE THREAD

**Issue by lzxb** [AlloyTeam/eslint-config-alloy#140]
否则声明的接口类型，不缩进

![image](https://user-images.githubusercontent.com/8424643/72063972-d939e000-3315-11ea-908f-d08617a3da94.png)

**Comment by xcatliu** [comment]
建议使用 prettier 自动修复格式错误
[eslint-config-alloy 不再维护 prettier 相关的规则了](https://github.com/AlloyTeam/eslint-config-alloy/blob/master/README.zh-CN.md#%E6%A0%B7%E5%BC%8F%E7%9B%B8%E5%85%B3%E7%9A%84%E8%A7%84%E5%88%99%E4%BA%A4%E7%BB%99-prettier-%E7%AE%A1%E7%90%86)

**Comment by lzxb** [comment]
Prettier 经常导致 pre-commit 钩子和vs code的编辑器中的换行规则不一致，导致合并代码的时候经常冲突了，所以被我弃用了。只能自己配置一下缩进的规则了。

**Comment by xcatliu** [comment]
嗯，那可以自行配置一下缩进规则哈
