### ISSUE TITLE
vue + ts 修饰符报错

### ISSUE THREAD

**Issue by bbct93** [AlloyTeam/eslint-config-alloy#141]
![image](https://user-images.githubusercontent.com/23315773/72680043-3c82f980-3af0-11ea-8ccc-979661db51aa.png)
按照你的配置  这个修饰符报错是什么原因  找了好多博客没有找到原因

**Comment by xcatliu** [comment]
这是 parsing error，eslint 编译错误。
我们这个配置暂时还不支持 vue + ts，可以谷歌一下其它人的 vue + ts 实践

**Comment by xcatliu** [comment]
vue + ts 统一在 #100 中跟进

**Comment by xcatliu** [comment]
@bbct93 已创建了一个 typescript-vue 示例 https://github.com/AlloyTeam/eslint-config-alloy/blob/master/README.zh-CN.md#typescript-vue
