### ISSUE TITLE
Configuration for rule "react/jsx-key" is invalid:

### ISSUE THREAD

**Issue by paohuoche** [AlloyTeam/eslint-config-alloy#148]
完全拷贝了 react + typescript 的 eslintrc.js 配置，报错，如下

<img width="641" alt="屏幕快照 2020-02-22 19 48 26" src="https://user-images.githubusercontent.com/7116988/75091818-77bf8f00-55ac-11ea-92b1-19643e539400.png">

**Comment by xcatliu** [comment]
eslint-plugin-react 版本过低吧

**Comment by qld-cf** [comment]
same error

**Comment by qld-cf** [comment]
update eslint-plugin-react eslint on local and global
it works
@paohuoche
