### ISSUE TITLE
[规则问题]array-callback-return

### ISSUE THREAD

**Issue by erasermeng** [AlloyTeam/eslint-config-alloy#15]
https://github.com/AlloyTeam/eslint-config-alloy/blob/9de217dc07f2a0d506353ba8eb749aa46a09f8f9/index.js#L160
https://github.com/AlloyTeam/eslint-config-alloy/blob/9de217dc07f2a0d506353ba8eb749aa46a09f8f9/index.js#L161

如果
Array.from
Array.prototype.every
Array.prototype.filter
Array.prototype.find
Array.prototype.findIndex
Array.prototype.map
Array.prototype.reduce
Array.prototype.reduceRight
Array.prototype.some
Array.prototype.sort

这些方法中没有`return`，那和`forEach`有什么区别呢？我认为这条规则应该限制，这些函数都是有`return`才生效。

**Comment by xcatliu** [comment]
同意，谢谢建议

**Comment by xcatliu** [comment]
注意，这个同时也限制了必须得 return 一个值，不允许直接 `return;` 或不写 return 语句
