### ISSUE TITLE
配置文件参数env和globals的疑问

### ISSUE THREAD

**Issue by pf135145** [AlloyTeam/eslint-config-alloy#151]
小白刚开始接触代码规范，最近接到一个给团队制定规范的任务，网上搜了一大圈感觉你们的这个整合的很好，想在团队内部使用。今天看了下文档，基本很容易理解，配合规则说明网站也很好找问题。就是配置文件中 env 和 globals 这两个属性没用看明白具体怎么配置，看了 eslint 的中文网也不是很明白，想问下可以给解释一下或者推荐个文章么，感谢🙏

**Comment by xcatliu** [comment]
配置了 env 之后，对于一些预置的全局变量就不会报错说未定义了。
globals 也类似，定义了一些全局变量
