### ISSUE TITLE
关于错误提醒问题

### ISSUE THREAD

**Issue by QQnumber** [AlloyTeam/eslint-config-alloy#154]
按照文档配置了一遍，功能生效了（保存代码自动修复）。但是eslint 的错误提示消失了。所以想问下问一下怎么恢复eslint的错误提示呢  ##样式相关的规则交给 Prettier 管理##

**Comment by QQnumber** [comment]
我使用的是react+ts

**Comment by xcatliu** [comment]
eslint 的错误提示怎么会消失呢？你把这一段错误的代码复制进去看看

```js
const foo = {
    set bar(value) {
        this.barValue = 'bar ' + value;
    }
};
```

**Comment by QQnumber** [comment]
> eslint 的错误提示怎么会消失呢？你把这一段错误的代码复制进去看看
> 
> ```js
> const foo = {
>     set bar(value) {
>         this.barValue = 'bar ' + value;
>     }
> };
> ```

emmm, 我晓得了，alloy 会对语法进行问题检测，而不会对代码格式做出报错提示。比如多余空格，单双引号。我之前纳闷的是 多余的空格，单双引号没报错提示。  谢谢回复。感恩。

**Comment by xcatliu** [comment]
嗯，格式上的规则都去掉了，改用 prettier 了。
若想要格式上的问题也标红显示，则可以使用 https://github.com/prettier/eslint-plugin-prettier
不过我觉得没必要红线显示，所以不建议使用。
