### ISSUE TITLE
[规则问题]no-div-regex

### ISSUE THREAD

**Issue by erasermeng** [AlloyTeam/eslint-config-alloy#16]
https://github.com/AlloyTeam/eslint-config-alloy/blob/9de217dc07f2a0d506353ba8eb749aa46a09f8f9/index.js#L212

[https://eslint.org/docs/rules/no-div-regex](https://eslint.org/docs/rules/no-div-regex)

原文是指正则表达式中不允许出现除法操作符，而不是不允许多余转义，实际上该规则推荐将`/=/`写为`/\=/`，建议开启该规则

**Comment by xcatliu** [comment]
确实描述有问题，我会改过来。

**Comment by xcatliu** [comment]
但是我觉得这个规则可以设为 `off`，因为有代码高亮的话，在阅读这种代码时，也完全不会产生歧义或理解上的困难：

```js
function bar() { return /=foo/; }
const foo = /=foo/;
```

**Comment by erasermeng** [comment]
@xcatliu 对，其实这个规则我看了半天才看懂，不过多转义一层总是没有坏处哈

**Comment by xcatliu** [comment]
多一层转义没坏处，不过也没必要强制必须转义吧
