### ISSUE TITLE
An import path cannot end with a '.ts' extension 

### ISSUE THREAD

**Issue by JackieAnxis** [AlloyTeam/eslint-config-alloy#164]
When I import a typescript file like:
```typescript
import * as interfaces from './interfaces.ts'
```
, it reports that `An import path cannot end with a '.ts' extension. Consider importing './interfaces' instead.`
![image](https://user-images.githubusercontent.com/19246028/82808236-2a5d0180-9ebc-11ea-80ea-52d30f937db3.png)

How can I support `'.ts'` extension?

**Comment by xcatliu** [comment]
Install [vscode deno](https://github.com/denoland/vscode_deno) plugin

**Comment by JackieAnxis** [comment]
I use both javascript and typescript in my project. So I override the eslintrc by:
```js
overrides: [
        {
            files: ['*.ts', '*.tsx'],
            extends: ['alloy', 'alloy/typescript'],
            parser: '@typescript-eslint/parser',
            plugins: ['@typescript-eslint/eslint-plugin']
        },
        {
            files: ['*.js'],
            extends: ['alloy'],
            parser: 'babel-eslint'
        }
    ]
```
Deno will disable the `overrides` configuration, my JavaScript files will be parsed by typescript parser.
![image](https://user-images.githubusercontent.com/19246028/82813590-ee2f9e00-9ec7-11ea-80f3-cc2c632ebc6a.png)

**Comment by xcatliu** [comment]
![](https://user-images.githubusercontent.com/19246028/82813590-ee2f9e00-9ec7-11ea-80f3-cc2c632ebc6a.png)

This is a tsc error (`ts(7006)`), not an eslint parse error.

This issue is not related with eslint. You should report an issue to deno.

**Comment by xcatliu** [comment]
Maybe setting `checkJs` to `false` in `tsconfig.json` will solve your problem

**Comment by JackieAnxis** [comment]
Got that, I'll report it to deno-plugin. Thanks a lot
