### ISSUE TITLE
从3.7.1升级到3.7.3之后报错

### ISSUE THREAD

**Issue by zouchengzhuo** [AlloyTeam/eslint-config-alloy#167]
1:1  error  Definition for rule 'default-case-last' was not found         default-case-last
 1:1  error  Definition for rule 'no-loss-of-precision' was not found      no-loss-of-precision
 1:1  error  Definition for rule 'no-useless-backreference' was not found  no-useless-backreference

**Comment by xcatliu** [comment]
需要升级 eslint 到最新版本

**Comment by IWSR** [comment]
所以这个是如何解决的？

**Comment by ssaylo** [comment]
同样遇到了这个问题，看了半天也没发现在哪里解决。

**Comment by IWSR** [comment]
@ssaylo 把项目内的eslint版本升上去

**Comment by ssaylo** [comment]
> @ssaylo 把项目内的eslint版本升上去
亲测有效，当时为何自己就没想起来这么弄呢？ 🤔
十分感谢。
