### ISSUE TITLE
ESLint cannot find definition for rules in CRA/TypeScript application

### ISSUE THREAD

**Issue by Stetchy** [AlloyTeam/eslint-config-alloy#168]
Hi,

Attempting to extend the config and the ESLint is showing errors surrounding the definitions for rules not being found, here is an example of the errors.

```
Definition for rule 'default-case-last' was not found.eslint(default-case-last)
Definition for rule 'no-loss-of-precision' was not found.eslint(no-loss-of-precision)
Definition for rule 'no-useless-backreference' was not found.eslint(no-useless-backreference)
```
The actual rules probably aren't of much significance.

I've tried two ways of extending the config:

1. Creating my own shareable-config with rules of my own, eg

```js
module.exports = {
  extends: ['alloy', 'alloy/react', 'alloy/typescript'],
  rules: {...}
};
```

then, in my `package.json` passing in:
```json
"eslintConfig": {
        "extends": "@company/eslint-config"
}
```

or by extending it in an .eslintrc.js.

2. Not using a shareable-config and extending the config directly in the package.json or an .eslintrc.js file.

Both scenarios cause the definitions for rules not found.

Any help is appreciated, thanks :)

**Comment by xcatliu** [comment]
The eslint version should above 7.2.0
Which eslint version do you use?

**Comment by Stetchy** [comment]
Using 7.2.0 in the shareable config and using the version of ESLint that comes with create-react-app.

**Comment by xcatliu** [comment]
I tried to use create-react-app to create a new proj, but still cannot reproduce your issue. Please

1. Try to exec `./node_modules/.bin/eslint --version` to checkout the eslint version.
2. Maybe your vscode is not using the eslint which installed in the project, have you ever seen an alert like this?

![image](https://user-images.githubusercontent.com/5453359/87683076-31fda000-c7b3-11ea-9999-be4cad565d67.png)

Last, it'll be helpful if you could submit a repo so I can download it and reproduce in my workspace

**Comment by Stetchy** [comment]
Reverting to version 3.7.0 seems to be a workaround for me, so perhaps the version of CRA I'm using is causing the issue, however I'm using the latest react-scripts, which should be coupled with the same eslint version as you'd use in CRA. Can you confirm you're using the CRA version of eslint?

**Comment by ssaylo** [comment]
Same probelm, and don't know how to solve...

**Comment by ssaylo** [comment]
Update your eslint and babel-eslint versions.

**Comment by xcatliu** [comment]
Now eslint-config-alloy support the latest version of eslint related packages, please upgrade all the npm packages
