### ISSUE TITLE
[规则问题]no-else-return

### ISSUE THREAD

**Issue by erasermeng** [AlloyTeam/eslint-config-alloy#17]
https://github.com/AlloyTeam/eslint-config-alloy/blob/9de217dc07f2a0d506353ba8eb749aa46a09f8f9/index.js#L215

目前前端比较受大家推崇的是扁平化的编码风格，减少不必要的else及else if会让整个代码结构更加扁平化，层级不那么深，当习惯了这种风格再看else及else if会非常难受，逻辑层次其实相对来说也不会差，建议开启规则：

`'no-else-return': ['error', { allowElseIf: false }]`

**Comment by lcxfs1991** [comment]
这条可能考虑禁止，将代码扁平化。

**Comment by xcatliu** [comment]
禁用这个规则有以下几个原因：

#### 1. 我觉得下面两种写法中，前者阅读起来更清晰：

```js
// 阅读起来结构清晰，层次分明，在同一个缩进层次下
function foo() {
    if (bar) {
        return doSomething();
    } else {
        return doOther();
    }
}
```

```js
// 没有前者结构清晰，特别是代码行数较多的时候
function foo() {
    if (bar) {
         return doSomething();
    }
    return doOther();
}
```

#### 2. early return 写多了之后，容易舍本逐末的想给每个 `if` 都加个 `return`，即使它根本不需要返回值

```js
// 正常写法，不需要返回值
function foo() {
    if (bar) {
        doSomething();
    } else {
        doOther();
    }
}
```

```js
// 为了 early return，而使 foo 有了返回值
function foo() {
    if (bar) {
        return doSomething();
    }
    doOther();
}
```

**Comment by erasermeng** [comment]
@xcatliu 这确实是一个有争议性的话题，强制开启可以让代码更加扁平化，依靠层次结构来表现清晰带来的好处可能抵不过else return所带来的可能层级嵌套很深带来的副作用。

前端的一个很重要的话题就是消除回调地狱，这条规则可以很有效的避免层级过深的情况，如果大家都遵循规范，我们将习惯于阅读扁平化的代码，清晰度不会比简单的缩进带来的清晰度差很多。

一般情况下early return用于处理一些异常情况，见过有人在if return后在else里面又进行异步调用，异步调用中再来个if else，这个时候如果能开启该规则，可以避免陷入回调地狱，我看到这样的代码会感到十分不舒服。

**Comment by xcatliu** [comment]
这条规则只有在 if 里面有 return 语句的时候才会生效，所以并不能有效的避免回调地狱。

避免回调地狱的方式，eslint 已经提供了：[max-nested-callbacks](https://eslint.org/docs/rules/max-nested-callbacks)
