### ISSUE TITLE
max-params类似的配置问题

### ISSUE THREAD

**Issue by Uyarn** [AlloyTeam/eslint-config-alloy#170]
您好，
    我们最近准备使用eslint-config-alloy，因为和我们的想法很一致，只检查语法、错误相关的问题，代码风格格式问题交给prettier。笔芯~
    但是有个问题想请教交流一下，像max-params设置3，complexity设置20这种规则配置，是出于什么考虑呢？为什么不是4，21之类的。

**Comment by xcatliu** [comment]
参考了很多资料，complexity 20 以上是难以维护的，所以设了 20。
max-params 3 已经够用了，超出的作为对象传，语义性更强

https://softwareengineering.stackexchange.com/questions/194061/cyclomatic-complexity-ranges

**Comment by Uyarn** [comment]
> 参考了很多资料，complexity 20 以上是难以维护的，所以设了 20。
> max-params 3 已经够用了，超出的作为对象传，语义性更强
> 
> https://softwareengineering.stackexchange.com/questions/194061/cyclomatic-complexity-ranges

了解了 感谢
