### ISSUE TITLE
eslint.autoFixOnSave is depreciated

### ISSUE THREAD

**Issue by tarokawada** [AlloyTeam/eslint-config-alloy#172]
Thanks for the configuration.

**Description**

VSCode setting `eslint.autoFixOnSave` is depreciated. The documentation for **_autoFixOnSave is not working_** and should be updated with the `editor.codeActionsOnSave` setting.

I'm willing to create a PR for this if that is fine for you :)

**Comment by xcatliu** [comment]
PR is welcome!

Thanks!

**Comment by tarokawada** [comment]
Updated the English documentation. Here is the PR #173. Thanks!
