### ISSUE TITLE
vue/component-tags-order

### ISSUE THREAD

**Issue by codesyofo** [AlloyTeam/eslint-config-alloy#174]
[vue/component-tags-order](https://eslint.vuejs.org/rules/component-tags-order.html)

这条的建议应该是`"order": [ [ "script", "template" ], "style" ]`这样的吧

**Comment by xcatliu** [comment]
属于 eslint-plugin-vue v7 的改动，升级 eslint-plugin-vue v7 依赖了 https://github.com/prettier/eslint-config-prettier/issues/161 ，所以等 eslint-config-prettier 更新后我这边再升级

**Comment by xcatliu** [comment]
已更新
