### ISSUE TITLE
希望文档备注一下版本号对应的vue版本

### ISSUE THREAD

**Issue by kangaroo711** [AlloyTeam/eslint-config-alloy#176]
因为3.x的vue还是beta, 线上项目都是2.x, 昨天安装了alloy发现一堆eslint语法提示, 就感觉比较莫名其妙, 然后查看了代码提交才发现是适配了3.0的vue, 可是项目是2.x的咋办呢? 只能回退版本, 而第一次使用alloy的用户应该会更加一头雾水体验不友好哦谢谢

**Comment by xcatliu** [comment]
感谢反馈！

稍后我会发布一个 eslint-config-alloy@4.0.0 版本，用来适配 vue 3.0
另外再发布一个 eslint-config-alloy@3.10.0 版本，保持大版本号为 3 的就是 vue 2.0，大版本号为 4 的就是 vue 3.0

会在 README 文档中说明

**Comment by xcatliu** [comment]
已发布 eslint-config-alloy@4.0.0 和 eslint-config-alloy@3.10.0
