### ISSUE TITLE
疑问: alloy 里面已经有了 eslint-config-xxx 依赖，再装一次的必要性是什么？

### ISSUE THREAD

**Issue by daolou** [AlloyTeam/eslint-config-alloy#178]
![image](https://user-images.githubusercontent.com/22312092/106580913-3fc31900-657d-11eb-97e1-e1c3104bc1a7.png)

如图，`eslint-config-alloy` 是含有 `eslint-config-react` 依赖的，再装一次的必要性是什么？另外 安装的和 `alloy` 内置的版本不一致会咋处理？

**Comment by iysf** [comment]
要是没有锁版本的话，只有一个npm包。

**Comment by xcatliu** [comment]
eslint-config-alloy 没有 eslint-config-react 的依赖。

那是 devDependencies
