### ISSUE TITLE
本地用 node 10.x 运行不了

### ISSUE THREAD

**Issue by daolou** [AlloyTeam/eslint-config-alloy#179]
![image](https://user-images.githubusercontent.com/22312092/107022623-9bd9a780-67e0-11eb-80c6-35ed9febf2b6.png)

可以给 package.json 增加一个 engines

**Comment by xcatliu** [comment]
看了下 package.json 中的 `engines`，似乎限制的是使用 eslint-config-alloy 的用户的 node 版本，而不是作为开发 eslint-config-alloy 需要的版本。故设置这里的 `engines` 不太合适，毕竟低版本 node 也是可以运行 eslint 的。
