### ISSUE TITLE
[规则问题]no-implicit-coercion

### ISSUE THREAD

**Issue by erasermeng** [AlloyTeam/eslint-config-alloy#18]
https://github.com/AlloyTeam/eslint-config-alloy/blob/9de217dc07f2a0d506353ba8eb749aa46a09f8f9/index.js#L248

业界大多数声音对这类奇技淫巧持反对态度，确实在一定程度上会破坏可读性。
至于性能，现代浏览器架构下也不一定不用位运算符性能就会差，且这种性能差距在一般业务中不会体现，只有在高性能计算场景才有明显的区别，以下是对单条语句做的测试：

![image](https://user-images.githubusercontent.com/8306959/33158349-3502085e-d044-11e7-9f2a-7188dfeeac47.png)
![image](https://user-images.githubusercontent.com/8306959/33158353-3e119130-d044-11e7-9dd7-a8a03118eddd.png)

建议开启该规则，不要让这类奇技淫巧充斥在我们的代码里

**Comment by lcxfs1991** [comment]
一直用着 !!~`xxx`.indexOf('xxx')

**Comment by erasermeng** [comment]
@lcxfs1991 我只用!!，ES7中的includes方法也是新的用来替代该写法的，该淘汰了

**Comment by lcxfs1991** [comment]
include得加pollyfill或者加额外的babel插件吧。

**Comment by erasermeng** [comment]
@lcxfs1991 现在babel已成为前端开发标配了吧

**Comment by lcxfs1991** [comment]
https://github.com/facebookincubator/create-react-app/issues/942

@erasermeng 

是标配，但babel不会将所有转换插件都加进preset里面的

**Comment by erasermeng** [comment]
@lcxfs1991 嗯，但是polyfill应该也是标配吧，像Promise、Object.assign这些都需要polyfill

**Comment by lcxfs1991** [comment]
为了控制体积大小，不是所有的都直接上polyfill的。

**Comment by xcatliu** [comment]
我也赞成开启这个规则，但是有一些写法还是很常见的

```js
var b = !!foo;
var b = ~foo.indexOf(".");
var n = +foo;
var n = 1 * foo;
var s = "" + foo;
foo += ``;
```

我觉得以上写法中 `!!` 可以允许

**Comment by erasermeng** [comment]
对，我也是这样建议！只允许布尔类型使用！！强制转换
