### ISSUE TITLE
请问为啥要在 typescript 中关闭 @typescript-eslint/no-unused-vars 规则？

### ISSUE THREAD

**Issue by bigbigbo** [AlloyTeam/eslint-config-alloy#182]
![image](https://user-images.githubusercontent.com/19587016/109938734-54750700-7d0b-11eb-93ef-465e21c0a431.png)

当我使用 alloy/typescript 规则扩展时，因为设置了 `'@typescript-eslint/no-unused-vars': 'off'`，以至于 eslint 无法检测 ts(x) 文件的未使用变量。

在 vscode 中，虽然设置 tsconfig.json 中的 `"noUnusedLocals": true, "noUnusedParameters": true,` vscode 也会黄色下划线高亮提示声明了但未读取值，但因为 eslint 没有检测到错误，导致这样的代码会被正常提交。

所以请问要怎么理解 `编译阶段检查就足够了`这句话，我除了自定义规则再把 `@typescript-eslint/no-unused-vars` 设置为 `true` 还有其他方法吗？是不是我哪里打开方式不对 😢

**Comment by xcatliu** [comment]
本意是觉得 tsconfig 的 noUnusedLocals 和 eslint 的 no-unused-vars 重复检查了，所以去掉了 eslint。

不过你说的有道理，下个版本会加上 eslint 的 no-unused-vars

**Comment by bigbigbo** [comment]
> 本意是觉得 tsconfig 的 noUnusedLocals 和 eslint 的 no-unused-vars 重复检查了，所以去掉了 eslint。
> 
> 不过你说的有道理，下个版本会加上 eslint 的 no-unused-vars

好的，感谢回答

**Comment by tylerlong** [comment]
这个规则貌似还是没加上啊。默认还是不会检查 unused vars.

**Comment by yijinc** [comment]
我也有同样的疑惑，我是在当前的 rule 又加回去了

**Comment by xcatliu** [comment]
@tylerlong @yijinc 抱歉一直忘加这个了。现在已经在 5.1.1 加回来了
