### ISSUE TITLE
假如在Vue项目中使用vue的Lint规则和TypeScript的Lint规则，该怎么配置？

### ISSUE THREAD

**Issue by iysf** [AlloyTeam/eslint-config-alloy#183]
如题...其实不是伸手党~~~

只是好奇，因为Vue的parser是vue-eslint-parser，假如Vue + TypeScript的话，得需要将parserOptions中的parser改为@typescript-eslint/parser才可以正常运行。

假如作者要设计这个功能的话，是需要单独发布一个npm包：eslint-config-alloy/typescript-vue 吗？

**Comment by iysf** [comment]
刚才找到了一个解决方式：

`.eslintrc.js`
``` js
module.exports = {
  root: true,

  extends: [
    '@ued/typescript',
    '@ued/vue',
    '@vue/typescript'
  ]
}
```

**Comment by xcatliu** [comment]
将统一在 #100 中解决

**Comment by xcatliu** [comment]
@iysf 已创建了一个 typescript-vue 示例 https://github.com/AlloyTeam/eslint-config-alloy/blob/master/README.zh-CN.md#typescript-vue
