### ISSUE TITLE
typescript Parsing error: Unexpected token, expected ","

### ISSUE THREAD

**Issue by dreamerblue** [AlloyTeam/eslint-config-alloy#184]
按照 vue + typescript 装了两个所需要的依赖，ts 文件在 lint 时报错。

复现代码：

```typescript
const x: object = { a: 1 };
const y: number = (x as any).a;
```

报错：

```
Parsing error: Unexpected token, expected ","

  1 | const x: object = { a: 1 };
> 2 | const y: number = (x as any).a;
    |                      ^
```

依赖版本：

```json
"@typescript-eslint/eslint-plugin": "4.4.1",
"@typescript-eslint/parser": "4.4.1",
"babel-eslint": "10.1.0",
"eslint": "7.11.0",
"eslint-config-alloy": "3.10.0",
"eslint-plugin-vue": "6.2.2",
"typescript": "3.8.3",
"vue-eslint-parser": "7.1.1"
```

vscode workspace 配置：

```json
{
  "typescript.tsdk": "node_modules/typescript/lib",
  "files.eol": "\n",
  "editor.tabSize": 2,
  "editor.formatOnPaste": true,
  "editor.formatOnSave": false,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "eslint.validate": ["javascript", "javascriptreact", "vue", "typescript", "typescriptreact"]
}
```

.eslintrc.js：

```javascript
module.exports = {
  extends: ['alloy', 'alloy/typescript', 'alloy/vue'],
  env: {
    // 你的环境变量（包含多个预定义的全局变量）
    //
    browser: true,
    node: true,
    // mocha: true,
    // jest: true,
    // jquery: true
  },
  globals: {
    // 你的全局变量（设置为 false 表示它不允许被重新赋值）
    //
    window: true,
    document: true,
  },
  rules: {
    // 自定义你的规则
  },
};
```

**Comment by iysf** [comment]
hello，你好~~~

运行之前请先执行以下命令：

``` bash
npm i @vue/eslint-config-typescript -D
```

请在 extends数组修改为以下格式，即可正常运行：

``` js
{
  extends: ['alloy', 'alloy/typescript', 'alloy/vue', '@vue/typescript']
}
```

**Comment by dreamerblue** [comment]
> hello，你好~~~
> 
> 运行之前请先执行以下命令：
> 
> ```shell
> npm i @vue/eslint-config-typescript -D
> ```
> 
> 请在 extends数组修改为以下格式，即可正常运行：
> 
> ```js
> {
>   extends: ['alloy', 'alloy/typescript', 'alloy/vue', '@vue/typescript']
> }
> ```

👍🏻 可以用

**Comment by xcatliu** [comment]
应该是因为 alloy/vue 使用的解析器是 `parser: 'babel-eslint'`，alloy/typescript 使用的解析器是 `@typescript-eslint/parser`

所以如果按照你这个次序：`extends: ['alloy', 'alloy/typescript', 'alloy/vue']` 就会最终使用 vue 的 parser，当然就解析不了 ts 语法了。

所以你换个次序应该可以： `extends: ['alloy', 'alloy/vue', 'alloy/typescript']`

**Comment by xcatliu** [comment]
将统一在 #100 中处理，会提供一个官方的配置方案

**Comment by zkqiang** [comment]
@xcatliu 更换次序后会出现如下报错：

![image](https://user-images.githubusercontent.com/32983588/128010761-ec1f2016-f8bf-494c-843e-56e6e4867101.png)

配置如下
```
  extends: ['alloy', 'alloy/vue', 'alloy/typescript'],
  plugins: ['unused-imports'],
```

没有另外指定 parser

**Comment by xcatliu** [comment]
@zkqiang @dreamerblue @iysf 已创建了一个 typescript-vue 示例 https://github.com/AlloyTeam/eslint-config-alloy/blob/master/README.zh-CN.md#typescript-vue
