### ISSUE TITLE
无法自动检测代码是否符合规则

### ISSUE THREAD

**Issue by Popxie** [AlloyTeam/eslint-config-alloy#187]
按照使用文档说明， 安装了依赖，生成了`.eslintrc`文件(默认数据)，然后启动项目，在代码中刻意输入不符合规则的代码，为啥没有任何提示且项目依旧正常运行？最开始使用vue项目自动配置的eslint时，会直接报错，结果改用`eslint-config-alloy`时没有任何效果、请问是我哪里出了问题嘛？此时`vscode`我没有进行任何设置。是我哪里姿势不对嘛？？？？？

**Comment by xcatliu** [comment]
创建一个 .vscode/settings.json 文件，然后贴入以下内容
