### ISSUE TITLE
[规则问题]no-invalid-this

### ISSUE THREAD

**Issue by erasermeng** [AlloyTeam/eslint-config-alloy#19]
https://github.com/AlloyTeam/eslint-config-alloy/blob/9de217dc07f2a0d506353ba8eb749aa46a09f8f9/index.js#L254-L255

之前维护过代码中有各种this的奇技淫巧，对于这种滥用this的行为比较抵制，会造成很难理解。

对于事件回调，如果用箭头函数，其实根本就没有那个this，依赖于浏览器的context我认为不是一个最佳实践，理应使用target或currentTarget获取DOM。

建议开启该规则

**Comment by xcatliu** [comment]
`this` 的灵活运用是前端必须掌握的吧，比如下面这种用法可以灵活的注入一些东西或调用一些方法，在一些库中还是挺常见的：

```js
function foo() {
    this.bar = 1;
}

const baz = {};

foo.call(baz);
```

**Comment by erasermeng** [comment]
@xcatliu 如你举的例子，我认为恰恰是一个反面例子，此时的foo函数会有以下几个特点：
1. foo函数中有this，又没有大写，让人看上去疑惑到底是一个构造函数还是普通函数？
2. foo不能被直接调用，要么调用call/apply/bind，要么使用new，直接调用就惨了，可能无端冒出个全局变量
3. 如果定义和调用是分离的，隔得比较远，其实这个函数就变得非常奇怪了。

所以建议在该用this时使用this，有其他方式时就不要使用令人费解的this了。
在我所看到的比较有名的开源框架或库的代码中，没有看到滥用this的写法，如果有，应该也是很早之前的版本了。不反对这类this原理上的探讨和理解，JS赋予了很强的灵活性，但同时也有很多糟粕，在工程中我们需要规范代码，去除一些糟粕，这正是代码规范存在的意义。

**Comment by xcatliu** [comment]
嗯有道理，结合我在我们代码仓库的实践，可以开启此规则。仅在必要的时候使用注释对单个文件关闭此规则即可。

**Comment by xcatliu** [comment]
最后参考了一下 airbnb 的规则，还是觉得 `this` 的用法有时是无可替代的，故还是决定关闭此规则，需要的话可以在自己的项目中开启。
