### ISSUE TITLE
prettier is conflicting with jsx-wrap-multilines rule

### ISSUE THREAD

**Issue by cookcc** [AlloyTeam/eslint-config-alloy#192]
[prettier is conflicting with jsx-wrap-multilines rule](https://github.com/prettier/prettier/issues/1009)
这类问题怎么解决？网上提供的方式 没不管用

**Comment by cookcc** [comment]
> [prettier is conflicting with jsx-wrap-multilines rule](https://github.com/prettier/prettier/issues/1009)
> 这类问题怎么解决？网上提供的方式 没不管用

希望改动的是prettier的配置，而不是将 jsx-wrap-multilines rule禁掉

**Comment by xcatliu** [comment]
就我所知，prettier 不提供，将来也不会提供这么细致的选项。既然选择用 prettier，就别管些格式规则了吧。
