### ISSUE TITLE
Cannot find module 'babel-eslint'

### ISSUE THREAD

**Issue by bigsma11** [AlloyTeam/eslint-config-alloy#193]
Error: Failed to load parser 'babel-eslint' declared in '.eslintrc.js » eslint-config-alloy » ./base.js': Cannot find module 'babel-eslint'

**Comment by xcatliu** [comment]
`babel-eslint` is deprecated, please use `@babel/eslint-parser` instead

**Comment by whwnow** [comment]
报这个错误是因为 4.2.0 的包没有发到 npm 上, 然而 readme 里的安装脚本已经是 `@babel/eslint-parser` 这个包了, 代码里引得还是 `babel-eslint`, 导致按照 readme 新安装的用户都会报错

**Comment by xcatliu** [comment]
确实是的，最后忘记发布了。
已发布。

**Comment by NieZhuZhu** [comment]
4.20 使用 https://github.com/eslint/eslintrc/blob/main/lib/flat-compat.js 进行配置拍平的时候遇到相同错误
```
Error: Failed to load parser '@babel/eslint-parser' declared in ' » eslint-config-alloy » ./base.js': Cannot find module '@babel/eslint-parser'

```
