### ISSUE TITLE
4.2.0版本next app编译（npm run build）报错

### ISSUE THREAD

**Issue by flyfinec** [AlloyTeam/eslint-config-alloy#195]
4.2.0版本next app编译（npm run build）报错，4.1.0没有该问题，如下如所示：
![image](https://user-images.githubusercontent.com/3030186/127256590-bdfd8736-1358-4732-9a25-a0e5436db597.png)

已经安装@babel/eslint-parser和@babel/preset-react依赖

**Comment by flyfinec** [comment]
应该是alloy/react和next的配置有冲突，next配置已经包含eslint-plugin-react和eslint-plugin-react-hooks

测试下面两种方案可以解决：
1. 配置为extends: ['alloy', 'alloy/react']，需要安装@babel/core
2. 配置为extends: ['alloy', 'next]，不会有上面报错

next的配置文档：
https://nextjs.org/docs/basic-features/eslint

**Comment by xcatliu** [comment]
`@babel/core` 是一个必须的依赖，我已补充到文档里了
