### ISSUE TITLE
使用alloy eslint检测无效

### ISSUE THREAD

**Issue by smartisantt** [AlloyTeam/eslint-config-alloy#197]
自己webpack搭建的项目
```
{
  "name": "wep",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "webpack --mode=development",
    "build": "webpack --mode=production"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "webpack": "^5.46.0",
    "webpack-cli": "^4.7.2"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.14.9",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.32.0",
    "eslint-config-alloy": "^4.2.0",
    "eslint-plugin-vue": "^7.14.0"
  }
}
```

.eslintrc.js 配置如下

```
// 文档 https://alloyteam.github.io/eslint-config-alloy/?language=zh-CN
module.exports = {
  extends: ['alloy'],
  env: {
  },
  globals: {

  },
  rules: {
  }
};
```

src 中的index.js 文件中，如下，没有报错
```
const foo = {
    set bar(value) {
      this.barValue = 'bar ' + value;
    },
  };
```

**Comment by xcatliu** [comment]
是运行脚本没有报错，还是 vscode 中没有报错？

**Comment by worrydog123** [comment]
我也遇到了同样的问题，没有使用自定义的规则
项目结构
![image](https://user-images.githubusercontent.com/38743211/162614285-aa04c4ef-603d-4716-b7ed-2cdc88ebda11.png)

.eslintrc.js
![image](https://user-images.githubusercontent.com/38743211/162613996-702f6499-5e8a-4799-9b4a-0e75bfa42ccd.png)

工作区，vscode配置
![image](https://user-images.githubusercontent.com/38743211/162614068-49792e02-fc8f-4dbc-a5df-71f343d5f304.png)
安装的依赖包
![image](https://user-images.githubusercontent.com/38743211/162614104-1719e684-df8c-414d-9d6f-4d22a127619d.png)
![image](https://user-images.githubusercontent.com/38743211/162614162-68927445-34fe-427b-bb56-7263677569aa.png)

只有ts的提示，没有那个自定义规则的提示
![image](https://user-images.githubusercontent.com/38743211/162614199-354764fc-b862-458f-bd97-173efb315ba2.png)

**Comment by worrydog123** [comment]
![image](https://user-images.githubusercontent.com/38743211/162617001-1ba95747-c2a2-4bf5-83d7-e1880819aae4.png)
原来是没有开启

**Comment by xcatliu** [comment]
@worrydog123 你的问题看上去已解决了。
@smartisantt 我先关闭 issue 了，请提供更多线索再打开 issue
