### ISSUE TITLE
alloy config报错找不到@babel/eslint-parser

### ISSUE THREAD

**Issue by 368573607** [AlloyTeam/eslint-config-alloy#198]
按照介绍进行了配置，只是把npm换成了yarn，配置好后，vscode就开始报错：

```
ESLint: Failed to load parser '@babel/eslint-parser' declared in '.eslintrc.js » eslint-config-alloy » ./base.js': Cannot find module '@babel/eslint-parser' Require stack: - /Users/xuhuading/Documents/browser-parser/node_modules/eslint-config-alloy/base.js. Please see the 'ESLint' output channel for details.
```

**Comment by 368573607** [comment]
![image](https://user-images.githubusercontent.com/60562136/131214313-36b14221-8654-45c5-96e1-9384ce2fd57e.png)

![image](https://user-images.githubusercontent.com/60562136/131214319-1b3f8fdc-68b3-415d-a185-722650c49b7c.png)

**Comment by xcatliu** [comment]
奇怪，你这不是安装了 `@babel/eslint-parser` 么？

**Comment by loveloki** [comment]
`node v16.9.1` 同样遇见这个问题，切换到 `14.17.5` 没有报错，好奇怪，目前先使用 `v14` 了

**Comment by MoonBegonia** [comment]
yarn add @babel/core -D 试试

**Comment by kyriejoshua** [comment]
我也遇到了类似问题，在 ts 的 react 项目中，而且在 node v16 和 v14 下都有。是 ts 用到的这个，`@typescript-eslint/parser` 找不到，但实际是安装了的。

package 内版本

"@babel/eslint-parser": "^7.16.3",
"@typescript-eslint/eslint-plugin": "^5.5.0",
    "@typescript-eslint/parser": "^5.5.0",
    "eslint": "^7.32.0",
    "eslint-config-alloy": "^4.4.0",
    "eslint-plugin-react": "^7.27.1",

报错内容
`ESLint: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.js » eslint-config-alloy/typescript': Cannot find module '@typescript-eslint/parser' Require stack: - /Users/node_modules/_eslint-config-alloy@4.4.0@eslint-config-alloy/typescript.js. Please see the 'ESLint' output channel for details.`

这个是 vscode 中的 Eslint 扩展抛出来的，和楼主类似。

**Comment by yutucc** [comment]
同问

用内置规则在一个空项目中尝试也是报一下错误：
```
Error: Failed to load parser '@babel/eslint-parser' declared in '.eslintrc.js » eslint-config-alloy » ./base.js': Cannot find module '@babel/core/package.json'
```

直接在空项目中
```
npm install --save-dev eslint @babel/eslint-parser eslint-config-alloy
```

执行 `eslint .` 后报错

或者使用 vscode 的 ESLint，通用报以上错误

**Comment by xcatliu** [comment]
`@babel/core` 是一个必须的依赖，我已补充到文档里了
