### ISSUE TITLE
对该项目的依赖有点疑问？

### ISSUE THREAD

**Issue by yves-zhou** [AlloyTeam/eslint-config-alloy#199]
为什么不把该项目的依赖写进dependencies里，而是需要开发者手动下载？

**Comment by xcatliu** [comment]
因为是一个 npm 包支持了不同的规则。如果不用 react 的话就不需要下载 react 相关的包了

**Comment by liuzhaowei55** [comment]
同样对这样的依赖管理感到困惑

**Comment by xcatliu** [comment]
已添加了 peerDependenciesMeta 和 peerDependencies，可以约束版本了
