### ISSUE TITLE
[规则问题]no-script-url

### ISSUE THREAD

**Issue by erasermeng** [AlloyTeam/eslint-config-alloy#20]
https://github.com/AlloyTeam/eslint-config-alloy/blob/9de217dc07f2a0d506353ba8eb749aa46a09f8f9/index.js#L313

不懂为什么会off掉这个规则，javascript:伪协议肯定是不使用为好啊，既影响性能，又不安全，和eval是一个性质。
为了一个javascript:void(0)而关闭整个规则？其实javascript:void(0)也不应该存在，这不是在做无用功吗，只有重构在写a标签时有可能用到，但完全可以preventDefault啊

**Comment by xcatliu** [comment]
没有 `href` 属性的 `a` 标签，与有 `href` 属性的 `a` 标签样式上会有差别，加上 `javascript:void(0)` 可以解决这个问题。

**Comment by erasermeng** [comment]
那个是写在html里，不在检验范围内，而且有href也可以直接prevent default ，不要采用javascript伪协议，感觉是美工时代的写法了

**Comment by xcatliu** [comment]
这个规则是用于限制使用 javascript 来设置 href 属性的，与在 html 里面设置 href 是一样的效果呀

**Comment by erasermeng** [comment]
@xcatliu 对啊，不能因为javascript:void(0)一个特例就把整个放开啊，就像有人只用eval来处理json，就把eval放开吗，既然有更好的替代方案为什么还要纠结于一种不好的写法呢？不使用`javascript:`这种不安全的伪协议应该达成共识吧。

**Comment by xcatliu** [comment]
嗯有道理，决定开启此规则。
