### ISSUE TITLE
eslint-config-alloy 4.3.0 breaks Vue build / TypeError: Cannot read property 'valueType' of undefined

### ISSUE THREAD

**Issue by iKnowMagic** [AlloyTeam/eslint-config-alloy#200]
In Vue 3, after upgrading to eslint-config-alloy 4.3.0, I started getting this error:

`TypeError: Cannot read property 'valueType' of undefined`, from: 
node_modules/eslint-plugin-vue/lib/rules/no-use-computed-property-like-method.js:131:18

The above-mentioned error prevents compilation to succeed, rendering the whole system unusable.

The problem goes away when downgrading to eslint-config-alloy 4.2.0

Thanks.

**Comment by icleolion** [comment]
Tracking this issue might prove useful: https://github.com/vuejs/eslint-plugin-vue/issues/1649

**Comment by xcatliu** [comment]
已创建了一个 typescript-vue 示例 https://github.com/AlloyTeam/eslint-config-alloy/blob/master/README.zh-CN.md#typescript-vue
