### ISSUE TITLE
Definition for rule 'react/no-unstable-nested-components' was not found

### ISSUE THREAD

**Issue by bigsma11** [AlloyTeam/eslint-config-alloy#201]
src/index.js
  Line 1:1:  Definition for rule 'react/no-unstable-nested-components' was not found  react/no-unstable-nested-components

之前没有这条报错, 新项目出现了, 请问是要自己在rules里添加这条规则吗?

**Comment by xcatliu** [comment]
需要升级 eslint 相关的包到最新版本

**Comment by bigsma11** [comment]
> 需要升级 eslint 相关的包到最新版本

  "devDependencies": {
    "@babel/eslint-parser": "^7.15.4",
    "@babel/preset-react": "^7.14.5",
    "eslint": "^7.32.0",
    "eslint-config-alloy": "^4.3.0",
    "eslint-plugin-react": "^7.25.2",
    "prettier": "2.4.1"
  }

刚新建了一个项目, 全部用 @latest 安装了一遍还是不行

**Comment by bigsma11** [comment]
> 需要升级 eslint 相关的包到最新版本

今天尝试了各种解决还是不行, `eslint-plugin-react` 和 `eslint-config-alloy` 试了前几个版本也不行

顺便 ReadMe 中 built-in 的安装会缺少 `@babel-core`, 应该是 
`npm install --save-dev eslint @babel/eslint-parser @babel/core eslint-config-alloy`

**Comment by xcatliu** [comment]
升级到最新版是可以的，你可能是用了全局的 eslint 而不是项目级的 eslint

`@babel/eslint-parser` 是包含了 `@babel/core` 的，不需要手动安装

**Comment by bigsma11** [comment]
> 亲测升级到最新版是可以的，你可能是用了全局的 eslint 而不是项目级的 eslint
> 
> `@babel/eslint-parser` 是包含了 `@babel/core` 的，不需要手动安装

用 `npm` 安装解决了, 用 `yarn` 会有问题, 可能是因为缓存
