### ISSUE TITLE
为什么不安装 @babel/eslint-parser  也能扫

### ISSUE THREAD

**Issue by NieZhuZhu** [AlloyTeam/eslint-config-alloy#202]

**Comment by NieZhuZhu** [comment]
ESLint 官方解析配置文件工具，解析这个规则集的时候如果不安装 @babel/eslint-parser 会失败。
既然强制指定需要安装 @babel/eslint-parser 是不是把他写到 dependencies 好一些呢？目前只在文档告诉用的人要安装 @babel/eslint-parser，但是不安装 @babel/eslint-parser 也能扫，但是不安装 @babel/eslint-parser  ESLint 在解析规则的时候又会报错，就很矛盾....
https://github.com/AlloyTeam/eslint-config-alloy/issues/193#issuecomment-895078594
![image](https://user-images.githubusercontent.com/44939961/135046463-766cc7db-c0bc-4f39-9520-62ad7acc0fce.png)

**Comment by NieZhuZhu** [comment]
https://github.com/AlloyTeam/eslint-config-alloy/blob/master/base.js#L28

**Comment by xcatliu** [comment]
没有写到 dependencies 里面去，是因为扫 ts 文件时，不需要 `@babel/eslint-parser`，而是另一个 parser：`@typescript-eslint/parser`

不安装 @babel/eslint-parser 时，报错信息不是很明确了吗？提示缺少模块 `@babel/eslint-parser`
