### ISSUE TITLE
vue3 + ts开发时 import type 遇到的问题

### ISSUE THREAD

**Issue by liuweiyibai** [AlloyTeam/eslint-config-alloy#203]
不好意思打扰了.

```ts
import type { StateType } from './state';
// lint检查时这里会报 no-unused-vars
export const hhLanguage = (state: StateType) => state.language + 'hhh';
```
如上代码，eslint 配置和 alloy文档中提供的一样，当使用 lint 检查时会报错 `no-unused-vars`，对于 type 定义部分 

```js
const state = {
  language: 'zhCN',
  currentActiveNav: '解决方案',
};
// lint 时这里会报 no-undef 
export type StateType = typeof state;
```

**Comment by xcatliu** [comment]
估计是缺少了 https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md
下版本加上

**Comment by xcatliu** [comment]
@liuweiyibai 已创建了一个 typescript-vue 示例 https://github.com/AlloyTeam/eslint-config-alloy/blob/master/README.zh-CN.md#typescript-vue
