### ISSUE TITLE
vue3.x+vite2.x jsx语法不支持

### ISSUE THREAD

**Issue by Lei233** [AlloyTeam/eslint-config-alloy#205]
请教一下这个问题怎么解决？
![image](https://user-images.githubusercontent.com/63794920/140721720-b081287e-5604-4c44-8723-be29a417a29f.png)

config如下：
![image](https://user-images.githubusercontent.com/63794920/140721832-ddabc410-b2e5-4e0a-8cdb-82bbde297d49.png)

**Comment by crank220** [comment]
@Lei233 楼主能看下你的webpack文件，我也是用的vue3.x+vite2.x，eslint不起作用

**Comment by xcatliu** [comment]
@crank220 eslint 和 webpack 没有关系吧

**Comment by Lei233** [comment]
> @Lei233 楼主能看下你的webpack文件，我也是用的vue3.x+vite2.x，eslint不起作用

vite编译不需要配置webpack啊

**Comment by crank220** [comment]
![image](https://user-images.githubusercontent.com/30229284/142136255-b4bae14c-53eb-403a-8498-36d1ee219104.png)
![image](https://user-images.githubusercontent.com/30229284/142136274-5904f7bd-32df-4dfa-ba5f-177bf580f725.png)
谢谢你的回复，抱歉，表达错了。是想看下package.json文件里面装了哪些依赖。目前按照vue下载了依赖，但一直提示未安装babel/core。安装babel/core后，eslint还是不起作用

**Comment by crank220** [comment]
感谢你的回复！抱歉，表达错了，原意是想看下package.json的配置。现在已经解决了eslint不起作用的问题了

**Comment by linjialiang** [comment]
好像大牛更加关注react，而不是vue3啊，但是vue3在中国确实比react用的人多很多了

**Comment by codesyofo** [comment]
解决了吗? 找到个评论说是
> 问题：jsx 语法不兼容
> 解决方案：@babel/eslint-parser 替换成 babel-eslint

**Comment by codesyofo** [comment]
@xcatliu https://github.com/babel/babel/issues/14546#issuecomment-1125020289

**Comment by xcatliu** [comment]
已创建了一个 typescript-vue 示例 https://github.com/AlloyTeam/eslint-config-alloy/blob/master/README.zh-CN.md#typescript-vue
