### ISSUE TITLE
import React from 'react';  eslint 报错

### ISSUE THREAD

**Issue by ashuihui** [AlloyTeam/eslint-config-alloy#206]
Definition for rule '@typescript-eslint/no-non-null-asserted-nullish-coalescing' was not found.eslint(@typescript-eslint/no-non-null-asserted-nullish-coalescing)
Definition for rule 'react/no-namespace' was not found.eslint(react/no-namespace)

**Comment by xcatliu** [comment]
所有 eslint 相关包升级到最新版即可
