### ISSUE TITLE
vue3 和 vue2 rules 冲突

### ISSUE THREAD

**Issue by beckZgh** [AlloyTeam/eslint-config-alloy#209]
rules: {
   'vue/no-v-model-argument': 'off',
   'vue/no-duplicate-attributes': 'off',
   'vue/no-v-for-template-key': 'off',
}

// package.json
"eslint-config-alloy": "^4.4.0",
"eslint-plugin-vue": "^8.2.0",

**Comment by xcatliu** [comment]
请描述清楚哪个冲突了？给出修改意见或者直接提个 pr 更欢迎

**Comment by xcatliu** [comment]
应该已经解决了，已去掉这些 rules
