### ISSUE TITLE
eslint-config-alloy@4.4.0(for Vue3) added Vue2 rule?

### ISSUE THREAD

**Issue by davidlin88** [AlloyTeam/eslint-config-alloy#210]
I understood that `eslint-config-alloy@4` is for "Vue.js 3.0" [from: Changelog](https://github.com/AlloyTeam/eslint-config-alloy/releases/tag/v3.10.0)

But I found an eslint error in my project: **"The template root requires exactly one element.eslint(vue/no-multiple-template-root)"** 

However, this rule is essential fro **Vue.js 2.x** [from: eslint-plugin-vue](https://eslint.vuejs.org/rules/no-multiple-template-root.html)

Is this reasonable?

### FYI
```
"vue": "^3.2.25"
"eslint": "^8.6.0",
"eslint-plugin-vue": "^8.2.0",
"eslint-config-alloy": "^4.4.0",
```
`.eslintrc.js`:
```js
const { defineConfig } = require('eslint-define-config')

module.exports = defineConfig({
  root: true,
  extends: ['alloy', 'alloy/vue'],
  env: {
    browser: true,
    node: true,
  },
  globals: {
    defineEmits: false,
  },
})

``

**Comment by xcatliu** [comment]
This is probably a bug, I'll fix it in the next version. Is there other rules only available in Vue2?

**Comment by davidlin88** [comment]
> This is probably a bug, I'll fix it in the next version. Is there other rules only available in Vue2?

vue/no-custom-modifiers-on-v-model
vue/no-multiple-template-root
vue/no-v-model-argument
vue/no-v-for-template-key
