### ISSUE TITLE
Cannot find module 'babel-eslint'

### ISSUE THREAD

**Issue by jptangchina** [AlloyTeam/eslint-config-alloy#212]
我的node版本是14.16.1，按照README操作后仍然提示Cannot find module 'babel-eslint'
Require stack:
- D:\opt\code\tieyouflightphoebus-vue\node_modules\vue-eslint-parser\index.js
- D:\opt\code\tieyouflightphoebus-vue\node_modules\@eslint\eslintrc\dist\eslintrc.cjs
使用的是Vue2，对应版本3.10.0

**Comment by Jiangmenghao** [comment]
我是这样解决的（一个思路，不一定对）

在 `.eslintrc.js` 中添加如下配置：

```
parserOptions: {
  parser: '@babel/eslint-parser'
}
```

**Comment by xcatliu** [comment]
这个问题比较奇怪，我还没能复现，先按评论的尝试下解决吧

**Comment by cNelf** [comment]
> 我是这样解决的（一个思路，不一定对）
> 
> 在 `.eslintrc.js` 中添加如下配置：
> 
> ```
> parserOptions: {
>   parser: '@babel/eslint-parser'
> }
> ```

报错问题解决了，但是eslint好像并没有生效？
能否看下你的.eslintrc.js配置
这是我安装的依赖：
"devDependencies": {
  "@babel/eslint-parser": "^7.17.0",
  "eslint": "^8.9.0",
  "eslint-config-alloy": "^3.10.0",
  "eslint-plugin-vue": "^8.4.1",
   "vue-eslint-parser": "^8.2.0",
}

**Comment by cNelf** [comment]
> > 我是这样解决的（一个思路，不一定对）
> > 在 `.eslintrc.js` 中添加如下配置：
> > ```
> > parserOptions: {
> >   parser: '@babel/eslint-parser'
> > }
> > ```
> 
> 报错问题解决了，但是eslint好像并没有生效？ 能否看下你的.eslintrc.js配置 这是我安装的依赖：
> 
> ```
> "devDependencies": {
>   "@babel/eslint-parser": "^7.17.0",
>   "eslint": "^8.9.0",
>   "eslint-config-alloy": "^3.10.0",
>   "eslint-plugin-vue": "^8.4.1",
>   "vue-eslint-parser": "^8.2.0",
> }
> ```

发现问题了，是因为没有安装 `@babel/core`，建议可以补充一下文档

**Comment by xcatliu** [comment]
@babel/core 确实是一个必要的依赖，我已补充到文档里了
