### ISSUE TITLE
都几个月过去了怎么没有更新

### ISSUE THREAD

**Issue by linjialiang** [AlloyTeam/eslint-config-alloy#215]
都几个月过去了怎么没有更新，[`eslint-plugin-vue`](https://github.com/vuejs/eslint-plugin-vue) 一直在更新

vue3+ts的应该加进去了

**Comment by xcatliu** [comment]
春节期间应该会更新的

**Comment by AisonSu** [comment]
还是没有更新哈哈哈哈哈哈哈哈哈

**Comment by xcatliu** [comment]
我回来啦！

**Comment by xcatliu** [comment]
已更新 4.5.0

**Comment by linjialiang** [comment]
@xcatliu  帅气
