### ISSUE TITLE
4.6.0 eslint 不兼容

### ISSUE THREAD

**Issue by yzw7489757** [AlloyTeam/eslint-config-alloy#226]
eslint version : "7.32.0"
原 ^4.5.1
自动升级至 4.6.0

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/28922129/176343593-2b93dfbb-b50e-4a97-9c6f-cdaf703f74bf.png">

解决方式：
通过 yarn 的 resolution 字段锁定 4.5.1 版本，问题解决。

**Comment by yzw7489757** [comment]
该规则增加于 [[5.22.0](https://github.com/typescript-eslint/typescript-eslint/compare/v5.21.0...v5.22.0)](https://github.com/typescript-eslint/typescript-eslint/compare/v5.21.0...v5.22.0#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR18) 

团队的 lint 包 @typescript-eslint/eslint-plugin 还处于 4.29.0 版本，导致不能兼容，是否应该增加 peer 来限制？

**Comment by xcatliu** [comment]
现在 eslint-config-alloy 是单包管理，如果添加 peer 需要把所有 plugin 都加上，但你用了 React 就肯定不会用 Vue，于是会导致 install 时 peer 报错缺少依赖。

要彻底解决这个问题，需要拆成多个包吧

**Comment by xcatliu** [comment]
我好像找到解决办法了，可以用 `peerDependenciesMeta`
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta

**Comment by xcatliu** [comment]
Fixed in 4.6.1

**Comment by Handpear** [comment]
@xcatliu 
现在可以同时配置 React 和 Vue 的规则吗，项目有需求混合开发，目前 eslint 会把 React 的 JSX 识别为 Vue 的 JSX

**Comment by xcatliu** [comment]
应该是可以的，如果有冲突，可以用 [overrides](https://eslint.org/docs/latest/user-guide/configuring/configuration-files#how-do-overrides-work) 来针对不同文件配置不同规则
