### ISSUE TITLE
[规则问题]init-declarations

### ISSUE THREAD

**Issue by erasermeng** [AlloyTeam/eslint-config-alloy#23]
https://github.com/AlloyTeam/eslint-config-alloy/blob/9de217dc07f2a0d506353ba8eb749aa46a09f8f9/index.js#L401

更倾向于每一个变量都应该初始化，应当有默认值，而不是只声明默认为undefined。

**Comment by xcatliu** [comment]
理想情况是这样比较好，可是现实却很难做到。。。

**Comment by erasermeng** [comment]
@xcatliu 嗯，我也发现了，有的时候是需要undefined的
