### ISSUE TITLE
如何继承 prettier 配置

### ISSUE THREAD

**Issue by Lyong0216** [AlloyTeam/eslint-config-alloy#230]
不是很理解和应用 eslint-config-alloy @3中针对 prettier 是使用介绍
创建一个 .prettierrc 文件，直接继承此配置：
`"eslint-config-alloy/.prettierrc.js"`
如何继承？

**Comment by xcatliu** [comment]
继承 => 复用

**Comment by xcatliu** [comment]
直接创建一个 prettier 配置文件 `.prettierrc`，然后填入内容

```
"eslint-config-alloy/.prettierrc.js"
```

**Comment by xcatliu** [comment]
具体可以看这里的说明 https://prettier.io/docs/en/configuration.html#sharing-configurations

<img width="842" alt="image" src="https://user-images.githubusercontent.com/5453359/180407784-9cde0c92-be2e-420c-a6e7-226972bf7dda.png">

**Comment by Lyong0216** [comment]
好的 感谢
