### ISSUE TITLE
规则的配置和描述不符

### ISSUE THREAD

**Issue by NieZhuZhu** [AlloyTeam/eslint-config-alloy#231]
![image](https://user-images.githubusercontent.com/44939961/183334868-a8f15f87-ea20-45cd-96db-031a8a1adf32.png)

**Comment by NieZhuZhu** [comment]
https://github.com/AlloyTeam/eslint-config-alloy/blob/master/typescript.js#L425

**Comment by xcatliu** [comment]
规则的描述是指「开启此规则的话，会有什么效果」

**Comment by xcatliu** [comment]
off 即表示未开启此规则
