### ISSUE TITLE
Alloy-typescript

### ISSUE THREAD

**Issue by B-Tanvir** [AlloyTeam/eslint-config-alloy#232]
React native typescript doesn't seem to work with Alloy-typescript configuration.

**Comment by xcatliu** [comment]
Hi Baha, thanks for report the issue, you provided too little information for me to respond.

Please provide your eslintrc, the error message or the steps to reproduce this issue, or a reproducible github repo could be most helpful

**Comment by B-Tanvir** [comment]
Thank you for your response,
https://github.com/B-Tanvir/nft-react-native

**Comment by xcatliu** [comment]
I tried this repo and eslint works correctlly.

BTW, it's recommended to install eslint in devDependencies

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/5453359/184769729-0c602c24-e93b-4896-882e-916b48034329.png">
