### ISSUE TITLE
README 文档的“在 VSCode 中使用”部分落后版本了

### ISSUE THREAD

**Issue by islinxuan** [AlloyTeam/eslint-config-alloy#236]
<img width="353" alt="eslint.probe & eslint.validate" src="https://user-images.githubusercontent.com/85301288/198914283-c6531f47-7faf-4f5e-9677-c188812e039c.png">

`eslint.probe` 这个规定 ESlint 插件需要校验的语言类型，默认包括 `.vue`、`.html` 等文件，只需要 `eslint-plugin-vue`、`eslint-plugin-html` 等包的支持。

`eslint.validate` 这个是老版本的定义校验的类型了。

**Comment by xcatliu** [comment]
感谢，`eslint.probe` 的默认值已经包含了大多数文件类型，故不需要再特殊配制了

**Comment by xcatliu** [comment]
已调整文档
