### ISSUE TITLE
为什么在vue.js中eqeqeq是off二不是error？

### ISSUE THREAD

**Issue by Cuixote** [AlloyTeam/eslint-config-alloy#238]
在[base.js](https://github.com/AlloyTeam/eslint-config-alloy/blob/32031a3e44c4f8bb9f5ee40e1770a497b4250f4d/base.js#L139)中`eqeqeq`是["error", "always"]，但是却被[vue.js](https://github.com/AlloyTeam/eslint-config-alloy/blob/32031a3e44c4f8bb9f5ee40e1770a497b4250f4d/vue.js#L129)中的`eqeqeq: "off"`覆盖。

**Comment by xcatliu** [comment]
这个是 eslint-config-alloy 的[构建脚本自动添加](https://github.com/AlloyTeam/eslint-config-alloy/blob/master/scripts/build.ts#L64)的。

因为 eslint-plugin-vue 的 eqeqeq 规则继承了 coreRule：

https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/rules/eqeqeq.js#L9
https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/utils/index.js#L505

**Comment by Cuixote** [comment]
不过如[vue-plugin-vue](https://github.com/vuejs/eslint-plugin-vue/issues/1503)所说，这并不是他们要做的事情，而应该是alloy 要做的事情。所以，我们要打开这条规则吗？

**Comment by xcatliu** [comment]
现在 vue 规则是关闭了 `eqeqeq` 开启了 `vue/eqeqeq`。这样子做会有什么问题吗？

<img width="444" alt="image" src="https://user-images.githubusercontent.com/5453359/211509219-d2df909c-a869-4f8f-929f-aaf29582d246.png">

**Comment by xcatliu** [comment]
因为 typescript 规则里，所有继承 coreRule 的规则，都需要先关闭 core rule 再开启 ts rule。所以这个构建流程也继承到了 vue 规则里

**Comment by Cuixote** [comment]
我的期望正如注释中所写**必须使用 === 或 !==，禁止使用 == 或 !=**，但是目前使用`extends: ["alloy", "alloy/vue"]`的配置。无论是在`*.js`文件或者在`*.vue`文件的`script`标签中，`==` 或者`!=`都不会出现ESLint的报错。

**Comment by Cuixote** [comment]
在我另一个使用了`extends: ["alloy", "alloy/typescript"],`配置的项目中，最终规则却是`"eqeqeq": [
      "error",
      "always"
    ],`，并且在`*.ts`和`*.js`中都是生效的，所以`vue/eqeqeq`这条规则，目前看来是有问题的。

**Comment by xcatliu** [comment]
在 `*.ts` 和 `*.js` 文件中不生效可能是有问题的，我考虑一下 vue 不要去使用 ts 同样的构建流程吧

**Comment by Cuixote** [comment]
> > 无论是在`*.js`文件或者在`*.vue`文件的`script`标签中，`==` 或者`!=`都不会出现ESLint的报错。
> 
> 在 `*.vue` 文件中应该是生效的，可以 clone 本项目，在这个文件 https://github.com/AlloyTeam/eslint-config-alloy/blob/master/test/vue/eqeqeq/bad.vue 中应该可以看到有报错信息

这个确实可以，但是是在`*.vue`文件的`template`中生效，并没有在`*.vue`文件的`script`标签中生效，建议你把这个测试用例中加入`script`的测试。

**Comment by xcatliu** [comment]
已修复，请下载 v4.9.0 版本
