### ISSUE TITLE
Typo: no-unused-vars

### ISSUE THREAD

**Issue by tylerlong** [AlloyTeam/eslint-config-alloy#239]
https://github.com/AlloyTeam/eslint-config-alloy/blob/e4572489add7e4d704531b330b5ef0960efb1a0c/typescript.js#L425-L430

既然说了必须使用，那为什么又是off？ 貌似只有TS才有这个问题。

在 base 里面的定义是正确的： https://github.com/AlloyTeam/eslint-config-alloy/blob/e4572489add7e4d704531b330b5ef0960efb1a0c/base.js#L772-L782

**Comment by xcatliu** [comment]
> 既然说了必须使用，那为什么又是off？ 「已定义的变量必须使用」，是对 `no-unused-vars` 规则的解释，`off` 表示关闭这个规则。
