### ISSUE TITLE
[规则问题]no-unused-vars

### ISSUE THREAD

**Issue by erasermeng** [AlloyTeam/eslint-config-alloy#24]
https://github.com/AlloyTeam/eslint-config-alloy/blob/9de217dc07f2a0d506353ba8eb749aa46a09f8f9/index.js#L444

对于`rest`写法，解构赋值时前面的参数可能没有用到，但却是必须要填写的，如：
```
var [ type, ...coords ] = data;
```
此时无论type是否用到，都需要填写该值。

建议配置为：
'no-unused-vars': ['error', { vars: 'all', args: 'none', ignoreRestSiblings: true }]

**Comment by xcatliu** [comment]
有道理，下个版本会改进，谢谢建议啦
