### ISSUE TITLE
TypeScript should disable "no-undef"

### ISSUE THREAD

**Issue by tylerlong** [AlloyTeam/eslint-config-alloy#241]
https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/linting/Troubleshooting.mdx#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors

> We strongly recommend that you do not use the no-undef lint rule on TypeScript projects. The checks it provides are already provided by TypeScript without the need for configuration - TypeScript just does this significantly better.

**Comment by xcatliu** [comment]
Disabled in 5.1.1
