### ISSUE TITLE
请问一下有没有对 typescript 5 的支持计划

### ISSUE THREAD

**Issue by aidenchen8** [AlloyTeam/eslint-config-alloy#244]
ts 5 正式版也发布了有一个月了，我看到 3 周前就有对 ts 5 支持的 commit 提交了，请问计划什么时候发布正式版支持 ts5 呢？

**Comment by xcatliu** [comment]
已支持 TypeScript 5.0
https://github.com/AlloyTeam/eslint-config-alloy/releases/tag/v5.0.0
