### ISSUE TITLE
为什么要启用这个 prefer-object-has-own 规则，有兼容性问题

### ISSUE THREAD

**Issue by git-lt** [AlloyTeam/eslint-config-alloy#248]
Object.hasOwn 是 es2022的标准，在移动端还有很多浏览器版本不支持，兼容性不太好，昨天自动替换为这个api上线后，导致了很多问题，被坑惨了，这种有兼容性问题的新API最好不要开启吧

**Comment by xcatliu** [comment]
确实是太新了，es2022 才出，已在 5.1.1 版本关掉。感谢反馈
