### ISSUE TITLE
consistent type export/import

### ISSUE THREAD

**Issue by alagunoff** [AlloyTeam/eslint-config-alloy#249]
Hi. Why do you have these rules off?
![image](https://github.com/AlloyTeam/eslint-config-alloy/assets/46949445/3b2d6106-942a-4188-b713-3b46c0daaea0)

**Comment by meteorlxy** [comment]
Hi, this repo is inactively maintained, so some new rules are turned off by default.

It does not mean that we don't recommend to use those new rules, so for now you can turn them on in your own project.

> BTW, I personally love this rule so I turned it on in my [personal eslint config](https://github.com/meteorlxy/configs/blob/af3ce7ecc22cb9b71ee830bc0d6e5e12d1055808/packages/eslint-config-typescript/lib/index.js#L54).
> I also suggest to turn on [no-import-type-side-effects](https://github.com/meteorlxy/configs/blob/af3ce7ecc22cb9b71ee830bc0d6e5e12d1055808/packages/eslint-config-typescript/lib/index.js#L89C25-L89C52) and [import/consistent-type-specifier-style](https://github.com/meteorlxy/configs/blob/af3ce7ecc22cb9b71ee830bc0d6e5e12d1055808/packages/eslint-config-typescript/lib/index.js#L112C6-L112C44)

**Comment by alagunoff** [comment]
Oh, thanks for the reply. I also love import plugin and will check suggested rules. Why is this project *inactively* maintained? I just came across your config and liked it very much) Especially your way of keeping it *up-to date* but hearing these news is bad.

**Comment by xcatliu** [comment]
@alagunoff Thanks for the suggestion, this rule should be turned on.

This repo is under maintenance and new versions are released every month.

**Comment by xcatliu** [comment]
Published in [5.1.2](https://github.com/AlloyTeam/eslint-config-alloy/releases/tag/v5.1.2)

**Comment by xcatliu** [comment]
The reason this rule was not enabled before is that the rule was "typeinfo required" before. Now it is not "typeinfo requered", so it can be enabled now.

**Comment by meteorlxy** [comment]
＞ This repo is under maintenance and new versions are released every month.

Happy to hear that 😁
