### ISSUE TITLE
[规则问题]no-confusing-arrow

### ISSUE THREAD

**Issue by erasermeng** [AlloyTeam/eslint-config-alloy#25]
https://github.com/AlloyTeam/eslint-config-alloy/blob/9de217dc07f2a0d506353ba8eb749aa46a09f8f9/index.js#L931

`var x = a => (1 ? 2 : 3);`
这种写法应该是可以被接受的，尤其是逻辑仅仅是一个三元表达式，不用多写括号和return。
建议配置为：

`'no-confusing-arrow': ['error', { allowParens: true }]`

**Comment by xcatliu** [comment]
同意

**Comment by xcatliu** [comment]
已修改
