### ISSUE TITLE
[feature] eslint rules conflict with mocha timeout

### ISSUE THREAD

**Issue by brick9527** [AlloyTeam/eslint-config-alloy#250]
When I write a mocha test script, it shows an error with `no-valid-this`

test demo:

```js
describe('my title', () => {
  it('test something', () => {
    this.timeout(1000);
    // do something...
  });
});
```

mocha timeout refference: [https://mochajs.org/#timeouts](https://mochajs.org/#timeouts)

**Comment by xcatliu** [comment]
You can turn off `no-invalid-this` in your eslintrc file.
Alternatively, a better approach would be to use ["override"](https://eslint.org/docs/latest/use/configure/configuration-files#how-do-overrides-work) to make it effective only in **/*.test.js files.

**Comment by brick9527** [comment]
已经收到邮件。我会尽快回复的。
