### ISSUE TITLE
什么时候会适配新的eslint.config.js

### ISSUE THREAD

**Issue by whwnow** [AlloyTeam/eslint-config-alloy#254]
如题，请问什么时候可以支持新的eslint模式，我在使用 `@antfu/eslint-config` 这个配置，他是新的，在引入 `eslint-config-alloy` 的时候，报错 `TypeError: Cannot redefine plugin "react".`

**Comment by xcatliu** [comment]
能给一下复现路径吗？

**Comment by whwnow** [comment]
当时两个一起用是因为 @antfu/eslint-config 的 js 支持不够友好。这两个应该不需要同时使用的，我关闭了
