### ISSUE TITLE
是否开个新坑呢?关于biomejs

### ISSUE THREAD

**Issue by you-hengh** [AlloyTeam/eslint-config-alloy#255]
简单描述一下biomejs

是eslint + prettier 的结合体, 而且是有Rust重构的,

网址: https://biomejs.dev/

而且Biome 赢得了 [Prettier挑战](https://biomejs.dev/blog/biome-wins-prettier-challenge) 的奖金！

希望大佬能继续分享biomejs的"一键规则"

**Comment by xcatliu** [comment]
了解了一下 Biome，前端工具 Rest 化确实是一个趋势，这方面 Boime 走的很快，基本上没有任何包袱的前进，估计更新迭代也会很快。
我准备持续关注一段时间，等它更稳定了功能更齐全了（比如支持了 Vue）再尝试吧
<img width="405" alt="image" src="https://github.com/AlloyTeam/eslint-config-alloy/assets/5453359/16c29fb6-2a8d-4402-a816-1655fdb11827">

**Comment by you-hengh** [comment]
是哦  确实如此  期待一波
