### ISSUE TITLE
提供的 example 无法使用

### ISSUE THREAD

**Issue by xqyi** [AlloyTeam/eslint-config-alloy#257]
此项目现在还有人维护吗？仓库里提供的 /examples/typescript-vue 中的例子无法使用：

1.  git clone  https://github.com/AlloyTeam/eslint-config-alloy.git
2.  cd eslint-config-alloy/examples/typescript-vue
3.  pnpm i （各个依赖性版本均按 package.json 原始配置版本安装）
     typescript 5.3.3  eslint  8.56.0
5.  pnpm eslint

直接提示错误：

![carbon](https://github.com/AlloyTeam/eslint-config-alloy/assets/3350573/7c9c4b1f-ad2e-45fa-ad76-20d0152d99ae)

根据提示在 .eslintrc.js 的 parserOptions 中添加 project 指向  './tsconfig.json' ，执行 pnpm eslint 后还是提示同样的错误提示

**Comment by xcatliu** [comment]
https://github.com/AlloyTeam/eslint-config-alloy/assets/5453359/8f498747-06f2-4177-b650-9d2e3d920b93

**Comment by xcatliu** [comment]
我试了下没问题呀，而且这个规则[consistent-type-assertions](https://typescript-eslint.io/rules/consistent-type-assertions)不是「Require Type Info」的，应该是不需要 project 配置的。

是不是 @typescript-eslint/eslint-plugin 的版本和我不一样？

我是 5.57.0

**Comment by xqyi** [comment]
基本确认了应该是某个依赖的包的版本不一致出现的问题，我将package.json中的依赖包全部升级到了最新版。
在自己的已有项目中使用时文档中的 npm i xxx 命令安装，出现问题可能也是某个依赖包版本太新了导致出现一些问题，package.json 中依赖包很多，只能一个一个和 example/typescript-vue 中的对比版本吗？
