### ISSUE TITLE
[规则问题]object-shorthand

### ISSUE THREAD

**Issue by erasermeng** [AlloyTeam/eslint-config-alloy#26]
https://github.com/AlloyTeam/eslint-config-alloy/blob/9de217dc07f2a0d506353ba8eb749aa46a09f8f9/index.js#L955

既然有更短的写法，为什么不采用呢，所谓规范就是要统一大家的写法，才更易阅读

**Comment by xcatliu** [comment]
有时常规写法和 shorthand 混用时，格式不工整：

```js
// bad
let a = {
  foo: window.x.y.foo,
  bar,
  baz: a.baz
};
```

```js
// good
let a = {
  foo: window.x.y.foo,
  bar: baz,
  baz: a.baz
};
```
