### ISSUE TITLE
[规则问题]prefer-rest-params

### ISSUE THREAD

**Issue by erasermeng** [AlloyTeam/eslint-config-alloy#27]
https://github.com/AlloyTeam/eslint-config-alloy/blob/9de217dc07f2a0d506353ba8eb749aa46a09f8f9/index.js#L970

arguments是类数组，真正使用时需要做一层强转，而rest恰恰就是其替代方案，arguments及arguments上的方法都将会过时，应推荐使用rest

**Comment by xcatliu** [comment]
`arguments.length` 用的还挺多的，用 rest 不方便
