### ISSUE TITLE
[规则问题]prefer-const

### ISSUE THREAD

**Issue by erasermeng** [AlloyTeam/eslint-config-alloy#28]
https://github.com/AlloyTeam/eslint-config-alloy/blob/9de217dc07f2a0d506353ba8eb749aa46a09f8f9/index.js#L961

prefer-const可以让代码一眼看上去就知道这个变量是不会被改变还是将会被改变，是一个好的实践方式，会提高可读性。

**Comment by xcatliu** [comment]
实际编码中，有的变量说不准将来会不会变，prefer-const 不合适。
而且在写代码的过程中，若启用了 prefer-const，则写下 `let foo` 的同时，编辑器就会提示 eslint error 了，很不方便。
