### ISSUE TITLE
typescript规则下，无法自动修复某些错误

### ISSUE THREAD

**Issue by jiangjiu** [AlloyTeam/eslint-config-alloy#30]
比如说结尾没有分号，在es规则下是可以通过快捷键自动修复的，但是typescript只会显示有错误，无法自动修复

**Comment by jiangjiu** [comment]
配置文件是按readme配置的，没有任何改动，eslint.validate也配置了typescript

**Comment by jiangjiu** [comment]
全局安装了eslint，项目本地也安装了，不知道会不会和这个有点关系？

**Comment by jiangjiu** [comment]
试了下，全局eslint --fix xxx.ts会报错，cannot find module ‘eslint-config-alloy’，
通过npm 命令来执行项目本地的eslint命令就好了。。。

看起来是vscode中的eslint插件如何识别本地或者全局问题

**Comment by jiangjiu** [comment]
查看了vscode-eslint，维护者说会优先local的eslint
我删掉全局eslint，看起来也是如此：
ts项目使用了ts规则，js文件是可以通过eslint快捷键自动修复的，ts文件关于es规则中的所有可修复规则都不能自动修复

**Comment by jiangjiu** [comment]
搞定了。。。好白痴的错误
eslint.validate需要这样写，而不是readme中的简写：
 {
            "language": "typescript",
            "autoFix": true
        },

**Comment by xcatliu** [comment]
试了下确实需要这么配置才行，谢谢啦~
