### ISSUE TITLE
使用eslint-config-alloy/vue的时候不支持动态import语法

### ISSUE THREAD

**Issue by Shenfq** [AlloyTeam/eslint-config-alloy#37]
vue.js文件中使用了vue-eslint-parser来做解析器，这会导致在解析script的时候不使用之前配置的babel-eslint，而默认的eslint的解析器不能识别动态import的语法。

相关issues：[https://github.com/eslint/eslint/issues/7764](https://github.com/eslint/eslint/issues/7764)

![image](https://user-images.githubusercontent.com/18613842/38789423-af2aef26-416c-11e8-82f7-c3523848258e.png)

通过配置parserOptions中的parser为babel-eslint可以解决这个问题。

[https://github.com/mysticatea/vue-eslint-parser#-options](https://github.com/mysticatea/vue-eslint-parser#-options)

![image](https://user-images.githubusercontent.com/18613842/38789441-c5b1f622-416c-11e8-91fc-d9ae56b71059.png)

**Comment by Shenfq** [comment]
[https://github.com/mysticatea/vue-eslint-parser#-options](https://github.com/mysticatea/vue-eslint-parser#-options)

**Comment by xcatliu** [comment]
感谢反馈，已更新
