### ISSUE TITLE
typescript/adjacent-overload-signatures

### ISSUE THREAD

**Issue by whosesmile** [AlloyTeam/eslint-config-alloy#38]
默认的typescript配置开启了规则: 

```javascript
    // 函数有重载时，必须将重载成员分组在一起
    'typescript/adjacent-overload-signatures': 'error',
````
然后校验我的代码报错，我不确定是否是eslint-plugin-typescript的问题，定位问题刚好看到你也在这个issue内：https://github.com/nzakas/eslint-plugin-typescript/issues/49

建议暂时将这个规则关闭掉，第一可能是typescript插件问题，第二当依赖第三方的库，然后根据需要在此基础上做扩展时，需要重载方法，这导致这条规则一定会报错。

**Comment by whosesmile** [comment]
补充下，可能我说的第二点不一定对：
报错原因没做过测试究竟是因为扩展后，单独添加的重载签名声明报错，还是确实因为重载签名在第三方的.d.ts文件中就不连续而报错；

**Comment by xcatliu** [comment]
这个规则确实还有问题，已关闭
