### ISSUE TITLE
Show message 'xxx' is assigned a value but never used. (no-unused-vars)

### ISSUE THREAD

**Issue by or4** [AlloyTeam/eslint-config-alloy#39]
Hi guys, thank you for this project, very useful!
![attach](https://user-images.githubusercontent.com/2460957/39405993-cfe98200-4bd9-11e8-8961-1987442a916c.png)
`
type Test = {
  some: any;
};

function Test(action: any) {
  console.log(action);
  return &lt;A extends Test&gt;(action: A) => (action);
}
`

**Comment by xcatliu** [comment]
Hi, this issue seems to be solved after recent upgradation of `typescript-eslint-parser`, please try to install it to the latest version.
```
npm i typescript-eslint-parser@15.0.0
```
