### ISSUE TITLE
加载项目时提示Cannot find module 'eslint-config-alloy/react'

### ISSUE THREAD

**Issue by kelekexiao123** [AlloyTeam/eslint-config-alloy#4]
eslint-config-alloy目录如下：
![qq 20170904095609](https://user-images.githubusercontent.com/17807197/30008994-45a8c62e-9157-11e7-838f-0b300b8f11f3.jpg)

**Comment by xcatliu** [comment]
你自己的项目的 `.eslintrc.js` 是什么内容呢？ESLint 版本号是多少呢？

**Comment by kelekexiao123** [comment]
在更新了eslint后弹出了若干警告
eslint-config-alloy/react: Configuration for rule "react/jsx-curly-spacing" is invalid: Value "[object Object]" must be an enum value. 
是否存在某些配置过期的可能性呢

**Comment by xcatliu** [comment]
升级一下 eslint-plugin-react 的版本号呢？

**Comment by kelekexiao123** [comment]
啊是的，的确是版本太旧导致的，我也不清楚为什么package.json里的版本号在重新install后没有更新...手动更改了版本号。
感谢感谢！
