### ISSUE TITLE
typescript 使用报错

### ISSUE THREAD

**Issue by ReconcileMySelf** [AlloyTeam/eslint-config-alloy#42]
在进行 typescript 验证是运行报错

![1530607413 1](https://user-images.githubusercontent.com/10515836/42209136-7cc85724-7ee0-11e8-9d6d-11ba88c78194.png)

**Comment by xcatliu** [comment]
没有安装 `babel-eslint`，请按[这个要求](https://github.com/AlloyTeam/eslint-config-alloy#typescript)安装所有需要的依赖
