### ISSUE TITLE
按步骤来，vscode的react还是没生效

### ISSUE THREAD

**Issue by YEXIAO419** [AlloyTeam/eslint-config-alloy#43]

**Comment by xcatliu** [comment]
可以按照这个方法调试下，看有没有什么报错：
https://ts.xcatliu.com/engineering/lint.html#vscode-%E6%B2%A1%E6%9C%89%E6%98%BE%E7%A4%BA%E5%87%BA-eslint-%E7%9A%84%E6%8A%A5%E9%94%99
