### ISSUE TITLE
TypeScript 规则不支持 cast

### ISSUE THREAD

**Issue by dreamerblue** [AlloyTeam/eslint-config-alloy#46]
发现如 (x as sometype) 这样的 casting 不支持，ESLint 会报错：`Parsing error: Unexpected token`。

这是我现在的 .eslintrc.js 配置：

```js
module.exports = {
  extends: [
    'eslint-config-alloy/typescript-react',
  ],
  globals: {
  },
  rules: {
    'react/jsx-indent-props': 'off',
    'typescript/member-ordering': 'off',
  },
  "parser": "babel-eslint",
  "plugins": ["typescript"]
};

```

**Comment by xcatliu** [comment]
TypeScript 规则已更新为 https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules
可以再试下此插件下是否会报错
