### ISSUE TITLE
no-control-regex 文档描述和已发布代码不一致

### ISSUE THREAD

**Issue by HakurouKen** [AlloyTeam/eslint-config-alloy#47]
[官方文档](https://alloyteam.github.io/eslint-config-alloy/) 和 [实际代码](https://github.com/AlloyTeam/eslint-config-alloy/blob/master/index.js#L68) 都是 `off`，然而 npm 官方源的最新版本(1.4.2)的对应值仍然是 `error`，对应 SHASUM: 7dcb015992a6598055679483103badf55534a0a6

对应的 commit: https://github.com/AlloyTeam/eslint-config-alloy/commit/abd87a9b4561ceba101aa3dafd16d5bb46670c8c

**Comment by xcatliu** [comment]
已更新，发布了新版 v2.0.0-alpha.1
