### ISSUE TITLE
Cannot find module 'babel-eslint'

### ISSUE THREAD

**Issue by HakurouKen** [AlloyTeam/eslint-config-alloy#48]
babel-eslint 应当加入 dependencies 或 peerDendencies

**Comment by xcatliu** [comment]
应该加入到 peerDependencies

**Comment by HakurouKen** [comment]
类似的，vue/react/typescript 等配置也需要对应的 plugin/parser。可以考虑像 airbnb-base 和 airbnb 规则一样，将 config 拆成几个 monorepo 管理（如：eslint-config-alloy-base / eslint-config-alloy-vue 等），这样可以针对不同的包指定不同的依赖。

**Comment by xcatliu** [comment]
已加入 peerDependencies，发布了新版 v2.0.0-alpha.1，感谢反馈！
暂时还没有达到需要使用 monorepo 的复杂度，所以目前不会使用哈
