### ISSUE TITLE
typescript-eslint-parser is  Deprecated

### ISSUE THREAD

**Issue by DiamondYuan** [AlloyTeam/eslint-config-alloy#49]

**Comment by xcatliu** [comment]
感谢反馈！我们团队内正在实践，近期会进行更新

**Comment by DiamondYuan** [comment]
> 感谢反馈！我们团队内正在实践，近期会进行更新

可以用 babel 解析 js 文件中的注释，然后自动生成 json，这样你们只需要维护规则就可以了。

https://github.com/DiamondYuan/interface-comments-parser

思路如上。

**Comment by xcatliu** [comment]
👍我们的另一个项目也是类似的方案
https://github.com/AlloyTeam/tslint-config-alloy

**Comment by DiamondYuan** [comment]
> 👍我们的另一个项目也是类似的方案
> https://github.com/AlloyTeam/tslint-config-alloy

我看到新闻说 TypeScript 官方决定全面采用 ESLint ,你们怎么看这件事情？


JavaScript 代码检验工具 ESLint 在 TypeScript 团队发布全面采用 ESLint 之后，发布 typescript-eslint 项目，以集中解决 TypeScript 和 ESLint 兼容性问题。而 ESLint 团队将不再维护 typescript-eslint-parser，也不会在 Npm 上发布，TypeScript 解析器转移至Github 的 typescript-eslint/parser。

**Comment by xcatliu** [comment]
当然是紧跟官方步伐，用 typescript-eslint 了

**Comment by DiamondYuan** [comment]
> 当然是紧跟官方步伐，用 typescript-eslint 了

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .

**Comment by DiamondYuan** [comment]
> 当然是紧跟官方步伐，用 typescript-eslint 了

我又一个脑洞，就是在 test 的时候，调用 GitHub API，获取 eslint / typescript-eslint 的全部 rule，和自己配置的 rule 进行比较。如果有新增的rule，就 test 失败。

**Comment by xcatliu** [comment]
脑洞大开哈哈
业界也有个方案，可以及时提醒 npm 包版本落后了 https://greenkeeper.io/

**Comment by xcatliu** [comment]
已更新了 v2.0.0-alpha.1，使用了 @typescript-eslint，加上了 greenkeeper，感谢反馈！
实现了完全由 test 构建出配置规则，感兴趣的话一起来建设吧！
