### ISSUE TITLE
JSX not allowed in files with extension '.tsx'eslint(react/jsx-filename-extension)

### ISSUE THREAD

**Issue by ibcLee** [AlloyTeam/eslint-config-alloy#58]
用eslint校验tsx文件，会提示
`JSX not allowed in files with extension '.tsx'eslint(react/jsx-filename-extension)`
怎么忽略掉这个warning呢

**Comment by xcatliu** [comment]
```
'react/jsx-filename-extension': 'off',
```

或者

```
"react/jsx-filename-extension": ["error", { "extensions": [".js", ".jsx", ".ts", ".tsx"] }]
```

**Comment by ibcLee** [comment]
@xcatliu  再问一下为什么eslint(@typescript-eslint/member-ordering)和eslint/sort-comp会同时校验呢？
`    "extends": ['eslint-config-alloy/react', 'eslint-config-alloy/typescript']`
我的eslintrc也没有定义eslint-config-alloy的规则

**Comment by xcatliu** [comment]
extends 后就有了 eslint-config-alloy 的规则了
