### ISSUE TITLE
valid-typeof 少写一种情况

### ISSUE THREAD

**Issue by dongyuanxin** [AlloyTeam/eslint-config-alloy#62]
除了  'undefined', 'object', 'boolean', 'number', 'string', 'function' 或 'symbol'， **基础类型新增了`bigint`**。

![image](https://user-images.githubusercontent.com/26399528/56470185-ce80a780-6475-11e9-8268-c6aa97ae1ce6.png)

**Comment by xcatliu** [comment]
ESLint 官方要等到 BigInt 到 stage4 才会加上支持。现在只到 stage3
可以考虑用 eslint-plugin-babel
https://github.com/babel/eslint-plugin-babel/issues/153

**Comment by dongyuanxin** [comment]
收到

**Comment by xcatliu** [comment]
亲测已修复
