### ISSUE TITLE
vue 项目, 安装后报错

### ISSUE THREAD

**Issue by xiaohaiH** [AlloyTeam/eslint-config-alloy#64]
错误提示
```bash
Parsing error: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>?
```
解决方法:
base.js 文件种 parser 属性放到 parserOptions 下就不提示这个报错了

**Comment by xcatliu** [comment]
能够给一下具体的 eslint 配置和复现步骤吗？

**Comment by xiaohaiH** [comment]
![image](https://user-images.githubusercontent.com/25895105/61128434-67a6e380-a4e4-11e9-9f5c-9082b09e326e.png)
![image](https://user-images.githubusercontent.com/25895105/61128451-71c8e200-a4e4-11e9-9e5f-00614a8e981a.png)
上图是项目中的配置, 没做过多的配置

**Comment by xcatliu** [comment]
你是使用到了 typescript 吗？
eslint-config-alloy 目前还不支持 typescript + vue

**Comment by xiaohaiH** [comment]
是的, 用上了,

**Comment by JoeyCurry** [comment]
typescript + vue准备什么时候支持呢，之前项目一直用eslint-config-alloy/vue，现在切换到typescript后发现没有好用的eslint规则了

**Comment by xcatliu** [comment]
@JoeyCurry 准备等 Vue 3.0 出来时再跟进

**Comment by xcatliu** [comment]
在 #100 中跟进

**Comment by sunhao0313** [comment]
@xcatliu  咱么样了兄弟，vue+ts的最佳实践～

**Comment by xcatliu** [comment]
@sunhao0313 等 vue 3.0 正式发布 && vue-eslint-plugin 支持 vue 3.0 之后，我会跟进

https://github.com/vuejs/vue-next
https://github.com/vuejs/eslint-plugin-vue

**Comment by xcatliu** [comment]
@sunhao0313 @JoeyCurry @xiaohaiH 已创建了一个 typescript-vue 示例 https://github.com/AlloyTeam/eslint-config-alloy/blob/master/README.zh-CN.md#typescript-vue
