### ISSUE TITLE
[no-unused-vars] 请教下，typescript导入interface报的no-unused-vars怎么解决

### ISSUE THREAD

**Issue by cadleo** [AlloyTeam/eslint-config-alloy#65]
typescript导入interface作为变量类型使用，但eslint似乎是将它识别为导入了变量，会报的no-unused-vars，怎么解决

**Comment by xiaohaiH** [comment]
关闭 eslint 的 no-unused-vars，开启 ts 的 
no-unused-vars 提示就行

**Comment by cadleo** [comment]
好的，3Q

**Comment by xcatliu** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/363

**Comment by xcatliu** [comment]
应该已修复

**Comment by HansJiang** [comment]
eslint-plugin-import

`   
 'import/resolver': {
      node: {
        extensions: ['.js', '.jsx', '.json', '.ts', '.tsx', '.d.ts'],
      },
    },
`
