### ISSUE TITLE
如果我的项目混用 js 和 ts，如何正确设置配置？

### ISSUE THREAD

**Issue by bigbigbo** [AlloyTeam/eslint-config-alloy#67]
因为当前项目是混用了 javascript 和 typescript 开发，如果同时设置
```js
extends: [
'eslint-config-alloy/react',
'eslint-config-alloy/typescript',
]
```
因为 typescript 使用的 parser 不是 babel-eslint，会出现我在 js 文件中使用新的 babel-plugin-proposal-optional-chaining 等插件提供的语法出现报错的问题。我现在是使用 tslint 来检测 typescript，但是tslint的规则实在是少，想用 eslint 统一做检测，但是又没法区分不同的文件后缀应用不同的配置，请问如何解决这个问题呢？

**Comment by xcatliu** [comment]
eslint 没办法在一个项目中针对不同后缀的文件使用不同的 eslintrc
js 文件和 ts 文件必须使用同一个 parser

**Comment by xcatliu** [comment]
你也可以在运行脚本的时候，指定不同的后缀使用不同的 eslintrc
但是只有运行脚本时有效，在 vscode 中还是只能识别一个 eslintrc

**Comment by bigbigbo** [comment]
> 你也可以在运行脚本的时候，指定不同的后缀使用不同的 eslintrc
> 但是只有运行脚本时有效，在 vscode 中还是只能识别一个 eslintrc

那好像针对这种情况没有特别完美的方案了，只能同时使用 Eslint 和 TsLint 了，或者项目统一切换至 TypeScript 了。

**Comment by LyCharlie** [comment]
现在应该可以根据不同的后缀使用不同的规则
``` json
"overrides": [
    {
      "files": ['*.js'],
      "parser": 'babel-eslint',
    },
    {
      "files": ['*.ts', '*.tsx'],
      "extends": ["plugin:@typescript-eslint/recommended"],
      "parser": '@typescript-eslint/parser',
      "plugins": ['@typescript-eslint/eslint-plugin'],
    },
  ]
```
https://github.com/typescript-eslint/typescript-eslint/issues/109

**Comment by chuntonggao** [comment]
> 现在应该可以根据不同的后缀使用不同的规则
> 
> ```json
> "overrides": [
>     {
>       "files": ['*.js'],
>       "parser": 'babel-eslint',
>     },
>     {
>       "files": ['*.ts', '*.tsx'],
>       "extends": ["plugin:@typescript-eslint/recommended"],
>       "parser": '@typescript-eslint/parser',
>       "plugins": ['@typescript-eslint/eslint-plugin'],
>     },
>   ]
> ```
> 
> [typescript-eslint/typescript-eslint#109](https://github.com/typescript-eslint/typescript-eslint/issues/109)

overrides 里面 不允许有extends

**Comment by LyCharlie** [comment]
eslint 6.0之后可以有

**Comment by Wangbaogang** [comment]
> 现在应该可以根据不同的后缀使用不同的规则
> 
> ```json
> "overrides": [
>     {
>       "files": ['*.js'],
>       "parser": 'babel-eslint',
>     },
>     {
>       "files": ['*.ts', '*.tsx'],
>       "extends": ["plugin:@typescript-eslint/recommended"],
>       "parser": '@typescript-eslint/parser',
>       "plugins": ['@typescript-eslint/eslint-plugin'],
>     },
>   ]
> ```
> 
> [typescript-eslint/typescript-eslint#109](https://github.com/typescript-eslint/typescript-eslint/issues/109)

如果js和ts是在vue单文件里是不是就没办法了？
