### ISSUE TITLE
[规则问题] '@typescript-eslint/no-this-alias'

### ISSUE THREAD

**Issue by daihaoxin** [AlloyTeam/eslint-config-alloy#68]
'@typescript-eslint/no-this-alias': 'error',  在对 this  进行解构的情况下，依然提示错误，如下图所示。

![image](https://user-images.githubusercontent.com/5250679/58086636-99d94a80-7bf1-11e9-9998-66803185ea2d.png)

**Comment by xcatliu** [comment]
请升级到 v2.0.0-alpha.3 即可解决
