### ISSUE TITLE
ts 3.5 以上版本大概什么时候提供支持

### ISSUE THREAD

**Issue by daihaoxin** [AlloyTeam/eslint-config-alloy#69]
---

WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.5.0

YOUR TYPESCRIPT VERSION: 3.5.1

Please only submit bug reports when using the officially supported version.
---

**Comment by xcatliu** [comment]
warning 可以不用管，本来就是支持的。
具体什么时候会去掉 warning 要看 [typescript-estree 的更新](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/typescript-estree#supported-typescript-version)

**Comment by xcatliu** [comment]
已支持
