### ISSUE TITLE
no-constant-condition这个规则注释有误

### ISSUE THREAD

**Issue by liruilong119** [AlloyTeam/eslint-config-alloy#7]
“禁止将常量作为 if, for, while 里的测试条件，比如 if (true), for (;;)，除非循环内部有 break 语句”这是你们给出的注释

1. `for (;;)`这种形式并没有将常量作为条件，这应该不是这规则所警告的

2. checkLoops为 false是指 允许在循环中使用常量表达式。而不是指“循环内部有 break 语句”就可以的

**Comment by xcatliu** [comment]
非常感谢指出错误！
