### ISSUE TITLE
关于 peerDependencies

### ISSUE THREAD

**Issue by Topthinking** [AlloyTeam/eslint-config-alloy#70]
为什么里面有`vue`还有`react`的lint依赖啊，这样我一个react项目每次安装依赖，都提示warning

```
eslint-config-alloy@2.0.0-alpha.2" has unmet peer dependency "eslint-plugin-vue@^5.2.2".
```

这让我们的日志看起来很不舒服啊，能不能想想办法

**Comment by xcatliu** [comment]
办法就是把这几个规则分别创建独立的包了，那样的话维护和使用起来会比较麻烦。

还有个办法就是去掉 peerDependencies，可是会缺失版本的提示

**Comment by xcatliu** [comment]
已去掉 peerDependencies

**Comment by xcatliu** [comment]
@Topthinking 已解决 peer 的问题，添加了 peerDependenciesMeta，设置成了 optional: true
