### ISSUE TITLE
ESLint: Failed to load config "eslint-config-alloy/react" to extend from. Referenced from: D:\.eslintrc.js. Please see the 'ESLint' output channel for details.

### ISSUE THREAD

**Issue by HuaHeShang1** [AlloyTeam/eslint-config-alloy#83]
ESLint: Failed to load config "eslint-config-alloy/react" to extend from. Referenced from: D:\.eslintrc.js. Please see the 'ESLint' output channel for details.

报这个错误，直接在项目中这样安装的：
npm install --save-dev eslint babel-eslint typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint-plugin-react eslint-config-alloy

**Comment by HuaHeShang1** [comment]
将配置文件放到项目中就可以了
module.exports = {

  extends: [
      'eslint-config-alloy/react',
      'eslint-config-alloy/typescript',
  ],
  globals: {
      // 这里填入项目需要的全局变量，暂无
  },
  rules: {
      // 这里填入项目需要的个性化配置
  }
};

**Comment by xcatliu** [comment]
报错时，是因为你是在 D:/.eslintrc.js 中配置的？

那可以全局安装一下吧：

```bash
npm install --global eslint babel-eslint typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint-plugin-react eslint-config-alloy
```
