### ISSUE TITLE
@typescript rule not found

### ISSUE THREAD

**Issue by jsonz1993** [AlloyTeam/eslint-config-alloy#97]
version: 
"@typescript-eslint/eslint-plugin": "^2.0.0",
"@typescript-eslint/parser": "^2.0.0",
"babel-eslint": "^10.0.2",
"eslint": "^6.2.1",
"eslint-config-alloy": "^2.0.5",

eslintrc.js
module.exports = {
extends: [
    'eslint-config-alloy/typescript',
  ],
}

TS的时候一直报这个问题，没有找到一些规则
"Definition for rule '@typescript-eslint/prefer-interface' was not found."

**Comment by midfer** [comment]
我也出现了相同的问题
Definition for rule '@typescript-eslint/no-angle-bracket-type-assertion' was not found.eslint(@typescript-eslint/no-angle-bracket-type-assertion)
Definition for rule '@typescript-eslint/no-object-literal-type-assertion' was not found.eslint(@typescript-eslint/no-object-literal-type-assertion)
Definition for rule '@typescript-eslint/no-triple-slash-reference' was not found.eslint(@typescript-eslint/no-triple-slash-reference)
Definition for rule '@typescript-eslint/prefer-interface' was not found.eslint(@typescript-eslint/prefer-interface)

可能是@typescript-eslint/eslint-plugin还不支持这几条规则吧
[https://www.npmjs.com/package/@typescript-eslint/eslint-plugin#supported-rules](url)

**Comment by xcatliu** [comment]
应该是一些规则被删除了，稍后我更新一下
https://github.com/typescript-eslint/typescript-eslint/issues/863

**Comment by jsonz1993** [comment]
嗯哼，我现在是暂时把那些给关了~

```javascript
      "@typescript-eslint/no-angle-bracket-type-assertion": 0,
      "@typescript-eslint/no-object-literal-type-assertion": 0,
      "@typescript-eslint/no-triple-slash-reference": 0,
      "@typescript-eslint/prefer-interface": 0,
```

**Comment by zzd258147** [comment]
https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.0.0
这里有提到：

- Removed deprecated rule prefer-interface. This rule was replaced by consistent-type-definitions.
- Removed deprecated rule no-triple-slash-reference. This rule was replaced by triple-slash-reference
- Merged both no-angle-bracket-type-assertion and no-object-literal-type-assertion into one rule - consistent-type-assertions.

**Comment by palashgdev** [comment]
@zzd258147 @xcatliu by turning off the rule I still see the warning in the console

**Comment by palashgdev** [comment]
Yeah CI/CD is freaking out :1234:

**Comment by Emiliano-Bucci** [comment]
Me too! having warnings about `Definition for rule '@typescript-eslint/no-angle-bracket-type-assertion' was not`. Any clues on this one?

**Comment by xcatliu** [comment]
@jsonz1993 @midfer @zzd258147 @palashgdev @brandonseydel @Emiliano-Bucci I've updated eslint-config-alloy to 2.1.0, please try the latest version. If there are any issues, please feel free to comment in this thread.

**Comment by Emiliano-Bucci** [comment]
@xcatliu Sorry but i've realized now that this is a particular `eslint` configuration. I'm having the warning using the default `typescript/eslint` configuration. You think that i can apply some change to fix this warning? Thanks! :)

**Comment by xcatliu** [comment]
@Emiliano-Bucci You can try to off some rules in eslinrc file

```
      "@typescript-eslint/no-angle-bracket-type-assertion": 0,
      "@typescript-eslint/no-object-literal-type-assertion": 0,
      "@typescript-eslint/no-triple-slash-reference": 0,
      "@typescript-eslint/prefer-interface": 0,
```

**Comment by mkotsollaris** [comment]
thanks @xcatliu `"@typescript-eslint/no-object-literal-type-assertion": 0,` did it for me.

**Comment by qld-cf** [comment]
凡是再出现这些问题，全部删除node_moduless 更新到最新, 记得加^
`
 "@typescript-eslint/eslint-plugin": "^2.27.0",
        "@typescript-eslint/parser": "^2.27.0",
`
